### ISSUE TITLE
Make output dir for EPUB relative to $base.dir [sf#134]

### ISSUE THREAD

**Issue by tomschr** [openSUSE/suse-xsl#10]
_From @tomschr on March 3, 2015 14:2_

**Reported by tom_schr on 2013-02-26 16:20 UTC**
At the moment, $base.dir is not really correctly implemented IMHO.

It is set to the "OEBPS/" string by default. This is very annoying as you set $base.dir to an absolute path and create all the files in it. You _have_ to change the directory before applying the stylesheets (as the Ruby dbtoepub script does).

TODO: Make all the parameters which rely on output directory or filenames relative to $base.dir ($img.src.path, $admon.graphics.path, $callout.graphics.path, etc.)

_Copied from original issue: openSUSE/daps#134_

**Comment by sknorr** [comment]
@tomschr Is this really a suse-xsl issue? Or is this actually a DAPS issue?

**Comment by tomschr** [comment]
As we don't support EPUB anymore, this is closed as won't fix.
