### ISSUE TITLE
ToC: Avoid page break within listing of <sect3/> items 

### ISSUE THREAD

**Issue by ghost** [openSUSE/suse-xsl#106]
Our tables of content look like this:

```
1     This 10
1.1   That 11
      Quirk 12   +   Quark 13   +   Quurk 15   +
      Querk 18
```

Occasionally, it happens that there is a page break at the following rather inopportune position:

```
1     This 10
1.1   That 11
      Quirk 12   +   Quark 13   +   Quurk 15   +

[page break]

      Querk 18
```

It would be great to avoid that.

**Comment by jsetz11** [comment]
Can't recreate the issue.

**Comment by tomschr** [comment]
Although you can keep things together, you end up with other, ugly outcome. We need to live with that, so it's a non-issue ATM.
