### ISSUE TITLE
Wrong includes in daps2013-ns, opensuse2013-ns 

### ISSUE THREAD

**Issue by sknorr** [openSUSE/suse-xsl#107]
Our build process does not take into account that the paths to included files may need to be adapted. Hence, `/usr/share/xml/docbook/stylesheet/daps2013-ns/xhtml/docbook.xsl` has an include for `../../suse2013/xhtml/docbook.xsl`.

Instead, that include should be for `../../suse2013-ns/xhtml/docbook.xsl`.

**Edit** In the below comment, Toms rightly remarked that I need to replace XInclude => include.

**Comment by tomschr** [comment]
Actually it's not a XInclude, but a normal include from XSLT. ;-)

Well, you are right. The `Makefile` needs to be adapted. Maybe a simple sed expression could help here.

On a more broader scale, I consider this one of the reasons to investigate more into #95.

**Comment by fsundermeyer** [comment]
Fixed with commit 4c3a1ea.
