### ISSUE TITLE
Layout: Always keep titles with following element, even if that is another title

### ISSUE THREAD

**Issue by ghost** [openSUSE/suse-xsl#110]
Would be good if constructs like

```
1 Blub

1.1 Blub Blub
```

were always kept on the same page.

**Comment by tomschr** [comment]
Possible solutions:

* Check in `sect1`, if the following child element after `title` is a `sect2`
  * if yes, add a `keep-with-next=always` attribute to the `sect1`
  * If no, do nothing (or the usual stuff).

or

* Check in `sect2`, if the previous parent element is a `sect2` and there is nothing in between parent and child.
  * if yes, add a `keep-with-previous=always` attribute to the `sect2`
  * If no, do nothing (or the usual stuff).
