### ISSUE TITLE
HTML+Saxon: No content

### ISSUE THREAD

**Issue by sknorr** [openSUSE/suse-xsl#125]
Saxon, in XML mode, closes empty script tags (and anything else you throw at it) this way:

```
<script/>
```

This is illegal in various interpretations of XHTML (technically, it is allowed in XHTML, but there is always the caveat that you have to serve it with the application/xhtml+xml MIME type and that this won't work in IE 7), they have to be closed like this:

```
<script></script>
```

**It should be noted that right now this only happens for single-html, since for chunked html we could solve this problem via the chunker.**

**Comment by sknorr** [comment]
@sknorr:
_The things that may work:_

1.  __<xsl:output method="saxon:xhtml"/>__: works correctly for single-html in saxon, but fails in xsltproc

     *    needs to be second-level element, so can't wrap it in xsl:template > xsl:if
     *    xsl:output's attribute values can only use an AVT in XSLT 1.1
     *    xsl:output must be self-closing, so can't use it with xsl:attribute
     *    However, Frank offered to add a DAPS quirk so that DAPS would rewrite our stylesheets on-the-fly to generate something Saxon-compatible (it would probably be fairly easy)
2.  Switching to .xhtml files and make sure, all server send out application/xhtml+xml MIME types for our documents
3.  Switching to HTML 4/5 should always work, XHTML is mostly dead anyway, _but_ this might stop us from being able to process our results to generate something fitting for ActiveDoc

_The things that don't work:_

1.  __<xsl:output method="xhtml"/>__: illegal expression in either processor (only html, xml or text generally allowed) [xsltproc still builds correctly]
2.  __<saxon:output method="[saxon:]xhtml" href="something.xml"/>__ doesn't fail in saxon, but doesn't seem to do anything; the href attribute is mandatory but hopefully harmless; curiously, this element must be within an xsl:template
3.  just __editing the make.script.link template__ (adding a comment that forces the closing </script>) – this just leads to even more unsettling results than a white page down the line (<a id></a>…)
4.  using __onechunk.xsl__, and setting chunker.output.method to saxon:html, as that breaks whenever a rootid is given (which is nearly always the case)

_What works:_

1.  running xmllint --format over the created file – but Frank hates this idea, arguing that we should output correct documents in the first place

**Comment by sknorr** [comment]
@tomschr:
saxon:output has nothing to do with xsl:output: the first can only be used in <xsl:template>s to output additional result documents apart from the main output stream; the second can only be used after xsl:stylesheet.

**Comment by sknorr** [comment]
@sknorr:
This appears to be down to the saxon-xslt script → Frank.

**Comment by sknorr** [comment]
@tomschr:
See https://sourceforge.net/p/daps/tickets/181/

**Comment by tomschr** [comment]
The easiest way is probably to throw an sed expression and replace any `<script/>` with `<script></script>`.  Keeps the XSLT headache low. :grin:

**Comment by sknorr** [comment]
I don't think there is any need to support Saxon. Closing.
