### ISSUE TITLE
Xrefs to should contain the name of the table too

### ISSUE THREAD

**Issue by ghost** [openSUSE/suse-xsl#131]
Xrefs to tables look like "Table 1" currently – they should contain the name of the table too.

Would maybe doing this via title="..." be more useful?, Tom asks

**Comment by tomschr** [comment]
I think, this is already the case, see the following image:

![screenshot_20170921_table](https://user-images.githubusercontent.com/1312925/30701556-d957a64c-9eea-11e7-91ab-4424bf3d71f2.png)

**Comment by sknorr** [comment]
This is (unfortunately) HTML-only -> reopen.

**Comment by tomschr** [comment]
Tested with Upgrade Guide, not relevant anymore.
