### ISSUE TITLE
Report Bug links everywhere!

### ISSUE THREAD

**Issue by ghost** [openSUSE/suse-xsl#134]
More elements that would profit from Report Bug links.
- Abstracts (would need to have an ID, then, which currently is unusual)
- Formal elements without titles (still need IDs)
- In chunked documents: Chapter headings (usually already have IDs)

**Comment by tomschr** [comment]
Ideas:

* The respective elements need IDs (otherwise we cannot make it work)
* The new layout suse2022 needs to be changed as well ("Report new issue" should be go to each element)

**Comment by tomschr** [comment]
Not relevant anymore.
