### ISSUE TITLE
Use Lazy Load plugin for JQuery

### ISSUE THREAD

**Issue by ghost** [openSUSE/suse-xsl#144]
(http://plugins.jquery.com/lazyload/) to improve performance (especially of single HTML) – if there is a way to do that without ruining the experience people that don't have JS activated 

```
<noscript><img ...></noscript>
<img src="loading"> + display:none"
```

Also make sure I don't impact Tomas's Drupal stuff.

**Comment by sknorr** [comment]
@sknorr:
More things we could do with images: https://hacks.mozilla.org/2013/03/capturing-improving-performance-of-the-adaptive-web/

**Comment by tomschr** [comment]
As we want to get rid of jQuery alltogether, this isn't relevant anymore so closing.
