### ISSUE TITLE
Add possibility to use analytics (Piwik?)

### ISSUE THREAD

**Issue by ghost** [openSUSE/suse-xsl#149]
We have one requirements here that would be relatively hard to get right: It would very much interest us what particular sections of a document people visit most (e.g. for RN or other single-page content). This could be hooked up via the animated scrolling code or it could be added via any prospective lazy-loading code.

For security-conscious/privacy-minded users this constant pinging might be a bit much to bear, though.

**Comment by janajaeger** [comment]
Is this still an issue or can we close this?

**Comment by tomschr** [comment]
From my point of view, this is already covered by our Analytics stuff. So yes, closing it.
