### ISSUE TITLE
Fix TOCs of books that contain articles

### ISSUE THREAD

**Issue by ghost** [openSUSE/suse-xsl#165]
We get

```
WARNING: toc : Unknown TOC element article
WARNING: toc : Unknown TOC element book                
WARNING: toc : Unknown TOC element article
```

and some complimentary layout issues.

(This is not too important for SUSE's use cases, but e.g. Martin from the community had issues with this.)

**Comment by tomschr** [comment]
This is comes from the `suse2013/fo/autotoc.xsl` stylesheet.

The TOC is done in the `susetoc` mode and it seems, there is a template missing for `article`.

**Comment by janajaeger** [comment]
Still relevant?

**Comment by tomschr** [comment]
Not relevant anymore.
