### ISSUE TITLE
Fix TOCs of sets

### ISSUE THREAD

**Issue by sknorr** [openSUSE/suse-xsl#166]
We get

```
WARNING: toc : Unknown TOC element book                
WARNING: toc : Unknown TOC element article
```
and complimentary layout issues.

This is not too important for SUSE's use cases, but e.g. Martin from SynDesk had issues with this.

**Comment by tomschr** [comment]
Duplicate as #165 
Probably we could combine them and close one bug.

**Comment by tomschr** [comment]
Closing as duplicate
