### ISSUE TITLE
legalnotice in articleinfo not displayed

### ISSUE THREAD

**Issue by ghost** [openSUSE/suse-xsl#168]
Bug!

**Comment by janajaeger** [comment]
Can you make sense of this, @tomschr ? Close, if it's fixed, close if you can't find out what was meant by this or fix, if this still isn't done.

**Comment by tomschr** [comment]
I did a small test with `<legalnotice>` and it works:

![Screenshot_20220712_125553](https://user-images.githubusercontent.com/1312925/178474784-a1ae61a8-1037-44c1-a798-382ecd9e4f40.png)

Closing it as fixed.
