### ISSUE TITLE
Investigate to what extent we want to support xrefstyle

### ISSUE THREAD

**Issue by ghost** [openSUSE/suse-xsl#170]
Our stylesheets currently support `xrefstyle` in a very limited capacity, at least where we have made downstream changes.

**Comment by sknorr** [comment]
Comment from the duplicate issue (#22):
_From @tomschr on March 3, 2015 17:51_

**Reported by tom_schr on 2013-12-06 14:36 UTC**
The HA guide contains in <tt>ha_nfs_quick_config_i.xml</tt> a kind of "mini toc" where xrefs are listed in an ordered list.

However, the xrefstyle attribute seems not to be recognized at all. The stylesheets resolve it always as

    Section "Defining Authentication Settings, Chapter 3, Installation and Basic Setup, High Availability Guide

With the xrefstyle attribute, the expected output would be:

    Section "Defining Authentication Settings"

Fixing it would probably also involve talking to upstream.


_Copied from original issue: openSUSE/daps#205_

**Comment by janajaeger** [comment]
@tomschr Can you investigate and determine what to do with this one?

**Comment by tomschr** [comment]
Not relevant anymore.
