### ISSUE TITLE
Figures can be wider than the page they are on.

### ISSUE THREAD

**Issue by ghost** [openSUSE/suse-xsl#171]
It's really uncool to have a figure that is wider than the page it is on.
See the OBS reference guide, page 23 (when built with FOP).

https://github.com/openSUSE/open-build-service-documentation

Of course, the author there did the wonderful thing of adding this there:

```
<imagedata fileref="maintenance_project_setup.png" width="800" />
```

This just reinforces the fact that I don't think we should trust the
height/width values we get from mediaobjects. (HTML resizes automatically, is that even possible in FO?)

**Comment by tomschr** [comment]
> It's really uncool to have a figure that is wider than the page it is on.

Yes,... but how should we deal with that?

I think, we shouldn't try to check for each and everything. It's always to find the right balance. In this case, I think we shouldn't limit the user too much. If he inserts garbage, he will get garbage. ;)

Apart from this, there might be situations were you *really* want to have something like "800".

**Comment by sknorr** [comment]
> If he inserts garbage, he will get garbage. ;)

https://softwareengineering.stackexchange.com/questions/12401#answer-12430

We already auto-resize images in HTML and it makes things easier for writers.

I think (hope) we should be able to compare page width and image width.

> I'm tempted to close this... 😉

Please don't.

**Comment by janajaeger** [comment]
@tomschr Implement a check or go for the pragmatic approach here?

**Comment by tomschr** [comment]
> I think (hope) we should be able to compare page width and image width.

You can't. 

The comparison itself is easy, of course. However, to get the **image width from the image itself** is not. This is one of the use cases where you can only do such a thing with extensions. Usually, they are written in C or Java.

We avoided these situations by using percent units. Coming back to the original request, "800" omitted the unit and it's basically "800px".

**Comment by tomschr** [comment]
As discussed, we think it's a GeekoDoc issue. Closing.
