### ISSUE TITLE
variablelist: too much space between term and following para

### ISSUE THREAD

**Issue by ghost** [openSUSE/suse-xsl#172]
## Problem

The space between the term (currently in bold) and its content is too wide. At the moment, the term looks like it belongs to the previous varlistentry instead of the current one.

See http://docserv.suse.de/documents/SLES12/SLES-admin/pdf/book.sle.admin_remarks_color_draft_meta_en.pdf (chapter Wi-fi).
![varlistentry](https://cloud.githubusercontent.com/assets/5476547/11692422/a4e16ab2-9e9f-11e5-9a27-bef48fdcbc61.png)

**Comment by janajaeger** [comment]
Looks very much fixed in 2022. Space between different items is now slightly bigger than the one between term and listitem. Closing this one.
