### ISSUE TITLE
Grid is unsuitably wide.

### ISSUE THREAD

**Issue by ghost** [openSUSE/suse-xsl#175]
Need more columns. Also, ideally, the grid should work on both Letter and A4

**Comment by janajaeger** [comment]
@tomschr Can you make sense of this and has this been dealt with in the meantime?

**Comment by tomschr** [comment]
PDF (and actually HTML to some degree) contains a _layout grid_ which is useful to align placements of lists and other block elements. It's a "nice to have", but we have more important issue.

**Comment by tomschr** [comment]
Not relevant anymore.
