### ISSUE TITLE
<orderedlist spacing="compact> might be a little too compact, …

### ISSUE THREAD

**Issue by ghost** [openSUSE/suse-xsl#179]
Do we actually have this attribute in SUSEDoc/NovDoc?

Also, on the contrary, normal lists may actually be spaced too loosely. Finding a happy medium would be pertinent.

**Comment by janajaeger** [comment]
@tomschr can you make sense of this and check whether this is an issue anymore?

**Comment by tomschr** [comment]
Well, yes. DocBook lists can be rendered in a "normal" mode and in a more "compact" mode. That's the `spacing` attribute for. The compact mode reduces the spacing between each consecutive list items.

I think we shouldn't allow this attribute and remove it in GeekoDoc. Or do you think we should keep it?

**Comment by tomschr** [comment]
Not relevant anymore.
