### ISSUE TITLE
Variablelist (with ID and Title) Permalink Overlaid by Other Things [sf#186]

### ISSUE THREAD

**Issue by tomschr** [openSUSE/suse-xsl#18]
_From @tomschr on March 3, 2015 15:26_

**Reported by taroth21 on 2013-10-17 12:46 UTC**
An itemizedlist with a title and an ID gets a permalink in the HTML output, whereas a variablelist (also equipped with ID and title) currently does not get one. I believe that treatment is unfair ;), therefore please fix it. 

_Copied from original issue: openSUSE/daps#185_

**Comment by tomschr** [comment]
**Updated by tom_schr on 2013-10-18 08:07**
- **status**: open --> pending
- **Info Provider**: Tanja Roth

**Comment by tomschr** [comment]
**Updated by tom_schr on 2013-10-18 12:13**
- **Info Provider**: Tanja Roth --> Stefan Knorr

**Comment by tomschr** [comment]
**Commented by tom_schr on 2013-10-18 12:13**
That's an interesting bug. :)

Permalinks are displayed as a hash mark (#). After looking into the generated XHTML code, the hash mark is there. For some reasons, it is not displayed correctly.

I've looked into Stefan's CSS file, but I can see any obvious bug. @Stefan, can you have a look?

**Comment by tomschr** [comment]
**Commented by *anonymous on 2013-10-21 11:29**
This happens because the variablelist title is overlayed by the varlistentry title below it. I.e., the browser renders it somewhat like this:

    ---------------------top of varlist title element--------
    
    ---------------------top of varlistentry title element --
    
    ACTUAL VARLIST TITLE #

    ---------------------bottom of varlist title element ----
    
    Varlistentry title
    ---------------------bottom of varlistentry title element


I did that, so given an ID, the HTML would scroll to the right position even though there is a bar at the top creating an offset. We will need to get rid of this somewhat gross hack.

**Comment by tomschr** [comment]
**Commented by sknorr on 2013-10-21 11:31**
I am sknorr, and I approve the message above.

**Comment by tomschr** [comment]
As far as I can see, this seems to be related to the JS script in [`suse2013/static/js/script.js`](https://github.com/openSUSE/suse-xsl/blob/develop/suse2013/static/js/script.js#L119-L137).

There you can see some lines which looks suspicious: The script touches the `href` and permalink. Maybe related, maybe not.

**Comment by taroth21** [comment]
BTW, in addition to variablelists, example with a title and an ID seem to have the same/a similar problem: the browser does not jump to the correct position even if there is  a permalink for the example (e.g. try, for example, jumping to 
http://docserv[...]/documents/SLE-HA12-SP1/SLE-HA-guide/single-html/#ex.ha.storage.protect.sbd-timings).

Also stumbled across another related bug today: https://bugzilla.suse.com/show_bug.cgi?id=912472

**Comment by sknorr** [comment]
This issue has nothing to do with the JS, and I also think it has nothing to do with XSLT. The issue should be entirely CSS-based. See also (https://trello.com/c/WJkSk8hJ).

**Comment by sknorr** [comment]
From me@Trello: "Some things are currently overlaid by unduly expanded elements. That stops people from clicking certain permalinks which is nasty."

**Comment by sknorr** [comment]
This looks like it was solved eventually. This is the modern version of Tanja's test page: https://documentation.suse.com/sle-ha/12-SP5/single-html/SLE-HA-guide/#ex-ha-storage-protect-sbd-timings
