### ISSUE TITLE
Make sure a page break occurs whenever a sect{1,2} occurs after 3/4s of the length of a page

### ISSUE THREAD

**Issue by ghost** [openSUSE/suse-xsl#183]
Tom tells me to look out for widows/orphans (these are line-based attributes). "Be careful setting it above 2 to 3 though."

There is no attribute that would tell FO to stop adding new sect1,2 after 3/4s of a page length.

**Comment by tomschr** [comment]
It's a "nice to have". Most of the time, the PDF is fine. For the time being, probably not important.
