### ISSUE TITLE
Find a way to apply the two-column page master to legal texts in articles

### ISSUE THREAD

**Issue by ghost** [openSUSE/suse-xsl#184]
Legal texts in articles are usually wrapped in a sect1 instead of in an appendix.

We'd like to always use two-columns for legal texts, both because that saves paper and because they are already printed very small, so two columns make them much more readable.

This works when when we have an appendix with role=legal, but it does not work on sect1, because these don't have a page break before.

Tom says, finding a way to do this in XEP would probably be relatively easy via an FO extension of XEP.
(But it wouldn't work in FOP.)

He adds that a generic solution would probably look rather unpretty in XSLT. (Maybe try writing to docbook-apps?)

**Comment by tomschr** [comment]
Not relevant anymore
