### ISSUE TITLE
Switch sans-serif font to something other than Open Sans?

### ISSUE THREAD

**Issue by ghost** [openSUSE/suse-xsl#195]
Open Sans is a screen font … it does not make me 100% happy to be using it for printable material

Check out (non-exhaustive list):
- Fira Sans (screen version of very successful print font)
- Roboto (screen font designed with high-resolution displays in mind, but totally different aesthetic)
- Linux Biolinum (pretty Optima-like)
- Adobe Source Sans (not sure if this one isn't too screen-optimised either)
- PT Sans (how screen-optimised is it?)
- _Clear Sans seems like a great option -- both screen and print-optimised, has Greek/Cyrillic and looks nice, if a bit sterile, is also a close-to-drop-in replacement for Open Sans_
- All Charis everywhere
- Noto Sans is also created for the screen and is in fact related and thus very similar to Open Sans, but covers a lot more languages

**Comment by janajaeger** [comment]
Still relevant in 2022?

**Comment by tomschr** [comment]
No, not really relevant anymore. We use Poppins now.
