### ISSUE TITLE
xsltproc has an issue with attribute-sets and inheritance

### ISSUE THREAD

**Issue by ghost** [openSUSE/suse-xsl#197]
See https://bugzilla.gnome.org/show_bug.cgi?id=704071
What to do – build everything with Saxon now? Can we get someone to fix this for us?

**Comment by tomschr** [comment]
libxml2 v2.9.3 was released on Nov 20 2015 but libxslt seems to be not updated since 3 years. :disappointed: 

Maybe use the latest libxml2 library and try it again. I have little hope that it will help, but it should be worth a try.
Another solution: talk to Markus so he can escalate it.

**Comment by sknorr** [comment]
We were recently updated to 2.9.3 and it is still broken there.

**Comment by tomschr** [comment]
This bug was fixed by Nick Wellnhofer on 2016-06-21 in [commit ca9edf237 of git.gnome.org](https://git.gnome.org/browse/libxslt/commit/?id=ca9edf237f9925de4af809f0d5a0ed7e55bb6c82) so closing it.

**Comment by sknorr** [comment]
Have you checked that the fix works?

**Comment by sknorr** [comment]
@tomschr ^

**Comment by tomschr** [comment]
@sknorr Yes, I've built the HA guides, both HTML and PDF, and didn't see any warning messages about recursive attribute sets.

**Comment by sknorr** [comment]
@tomschr But this issue has nothing to do with recursive attribute sets...

**Comment by janajaeger** [comment]
Still relevant?

**Comment by tomschr** [comment]
Not relevant anymore
