### ISSUE TITLE
Error concerning hyphenation patterns for CJK languages

### ISSUE THREAD

**Issue by ghost** [openSUSE/suse-xsl#199]
FOP shows this when building zh_CN books:

```
org.apache.fop.hyphenation.Hyphenator getHyphenationTree
SEVERE: Couldn't find hyphenation pattern for lang="zh_cn".
```

Obviously, Chinese is not hyphenated. However, there is a good bit of English content in our Chinese books, so maybe it would make sense to try to use the English hyphenation patterns for Chinese? Not sure.
On the other hand, maybe this message goes into hiding when we stop setting hyphenation properties on Chinese content.

**Comment by tomschr** [comment]
Not relevant anymore.
