### ISSUE TITLE
Check what our story is regarding embedding SVG in HTML

### ISSUE THREAD

**Issue by ghost** [openSUSE/suse-xsl#203]
https://sourceforge.net/p/daps/discussion/General/thread/22053bac indicates there might be an issue with SVG support in at least one of our stylesheet. In any case, it might be worth checking what happens when you try to embed SVGs in HTML.

If we then create `<object>` tags: we should use `<img>` instead. Ideally, we could also use SVGeezy, but that would depend a little on DAPS.

**Comment by sknorr** [comment]
SVGeezy should at this point be unnecessary, since all the browsers have SVG support. We still have not tested embedding much yet, however.

**Comment by tomschr** [comment]
Not relevant anymore.
