### ISSUE TITLE
If link has text, put link text in footnote by default?

### ISSUE THREAD

**Issue by sknorr** [openSUSE/suse-xsl#204]
Consider a para containing text like:

```
...I have <link xlink:href="example.pdf">an example document</link> here. And there is also ...
```

If the href attribute had a length in the hundreds of characters that would lead to text flow being broken completely, if if the user was not interested in the link. Which is not good. Currently, our guideline is to put links into a "For More Information" section where possible.

However, that may not always be possible... So, maybe, when such a link appears inside a para, it might be best to add a footnote containing the link text...

**Comment by tomschr** [comment]
You can get links/ulinks in footnotes by using the [`ulink.footnote`](http://docbook.sourceforge.net/release/xsl/current/doc/fo/ulink.footnotes.html) parameter.

Currently, this is not supported by our stylesheets.

**Comment by sknorr** [comment]
Let's not pursue this. Closing.
