### ISSUE TITLE
Compare size of chapter headings compared to sect1 headings

### ISSUE THREAD

**Issue by ghost** [openSUSE/suse-xsl#207]
...these look eerily similar. Not sure if these actually have the same size but it almost looks like that is the case.
[In books, e.g. check AutoYaST Guide, chapter 2 or 3 where those titles immediately follow each other.]

**Comment by sknorr** [comment]
These are both the same at 20px, even though chapter should be at 24px. 24px is even set in a certain `fo:block` around chapter but then overwritten by another child `fo:block`.

**Comment by tomschr** [comment]
It's still the case. However, to avoid overly long lines (which may break), we leave it as is.
