### ISSUE TITLE
Create less obtrusive version of admonitions for use in lists, tables

### ISSUE THREAD

**Issue by ghost** [openSUSE/suse-xsl#211]
Sometimes, our current admonitions (especially in PDF) are a bit too heavy when used within lists (e.g. in variablelists where the title of the admonition is larger than the term entry in the list) or tables (where the use of admonitions is doubtful anyway).

This is most relevant for PDFs, in HTML, the font size of the title does not actually vary. and the icons are a bit less prominent. Nevertheless, for HTML, it would be good to see if we can reduce the border around admonitions etc.

**Comment by sknorr** [comment]
First implementation done with 0aa05c315a348a5371896eeb38df129d6496a547.

**Comment by tomschr** [comment]
We should avoid admonitions in tables anyway. In lists it is still possible. Nevertheless, it's a minor issue and not relevant
