### ISSUE TITLE
DAPS's --meta feature is wonky in DB5 docs

### ISSUE THREAD

**Issue by ghost** [openSUSE/suse-xsl#214]
@fsundermeyer reports that in SUSE Cloud 6/Deployment, it seems to work in some files, but not in others. @keichwa reports SUMA 3/Reference that it barely works for chapters and not at all for sect1s, sect2s, etc.

**Comment by janajaeger** [comment]
@fsundermeyer can you make sense of it or is it safe to close this one?

**Comment by fsundermeyer** [comment]
We used to have a feature with which we could display SVN metadata in draft mode (HTML and PDF). When switching to git this no longer worked, but at least "filename" and ID were displayed.
This no longer worked reliably when switching to DB5.
This would need to be implemented for the dm tags if we would want to implement it properly. Use case was to make reviews easier when reading PDF or HTML. We may also drop it entirely (would also require a ticket in DAPS to remove the feature from DAPS).

**Comment by tomschr** [comment]
Not relevant anymore for us.
