### ISSUE TITLE
Sanitize title display in PDF sidebar ToC and xref

### ISSUE THREAD

**Issue by ghost** [openSUSE/suse-xsl#219]
Items of the PDF ToC (i.e. in most applications, the ToC in the sidebar) do not go through a step where spaces are removed from the start and the end, unlike titles that are used elsewhere (on-page ToC, or actually as the heading of a section). Unfortunately, then, there is a visible difference between

```
<title>
  My Title
</title>
```

and

```
<title>My Title</title>
```

I.e.:

```
1.0  My Title
```

v/

```
1.0 My Title
```

Same issue appears in xrefs to a title with spaces around it.
- [ ] PDF sidebar ToC
- [ ] xrefs to elements with such titles (both PDF and HTML)

**Comment by tomschr** [comment]
For the records: The workaround to avoid this bug is to remove any whitespace after `<title>` and before `</title>`.

**Comment by tomschr** [comment]
Not relevant for 2022 stylesheets anymore.
