### ISSUE TITLE
Be more lenient/give helpful message when validating table markup

### ISSUE THREAD

**Issue by ghost** [openSUSE/suse-xsl#222]
In Suma/develop, there was this issue and no one saw it because our stylesheets do not give so much as an error message for this:

```
--- a/xml/quickstart3_chap_install_overview.xml
+++ b/xml/quickstart3_chap_install_overview.xml
@@ -157,9 +157,10 @@
             &susemgr;. If you plan on using the new Salt features, ensure your clients are
             supported.</para>
         <informaltable>
-            <tgroup cols="2">
+            <tgroup cols="3">
                 <colspec colname="c1"/>
                 <colspec colname="c2"/>
+                <colspec colname="c3"/>
                 <thead>
                     <row>
                         <entry>
```

I am not sure if it is a good idea to outright do the obvious and work with the number of entries instead of the colspecs/tgroups here. We probably just want an error message...

**Comment by tomschr** [comment]
I guess, this is something for upstream. If I'm not mistaken, there could be a Schematron rule. If not, we could/should create one...

**Comment by sknorr** [comment]
We do not use Schematron right now... so doing that wouldn't have any benefit without the larger effort of also providing Schematron validation in DAPS.

**Comment by janajaeger** [comment]
@tomschr what's the 2022 take on this one? Any news?

**Comment by tomschr** [comment]
It still correct, tables are a pain to validate. We have a Python script now for table validation. It could be improved, but we move on.
