### ISSUE TITLE
Gib dem Kind einen Namen, der nicht SUSEDoc ist

### ISSUE THREAD

**Issue by sknorr** [openSUSE/suse-xsl#232]
Currently our DocBook 5-based schema is called SUSEDoc. That is unfortunate because the software `susedoc` was a precursor of DAPS. While `susedoc` itself is not in use any more, there are still SVN repos etc.

To avoid any confusion, we should find a different name for the schema.

Proposals:

* SUSE Custom DocBook (SCD)
* SUSE-customized DocBook (SCD)
* SUSEbook Schema (SBS?)
* SUSE Stringent DocBook (no abbreviation)
* SUSE Streamlined DocBook (no abbreviation)
* ...

**Comment by tomschr** [comment]
What about "SUSE-Schema"? Could be abbreviated with SUSa :grinning:

**Comment by sknorr** [comment]
The abbreviation does not quite sit right with me. The name also does not allude to documentation in any way.

**Comment by tomschr** [comment]
SUSE[-]Doc-Schema?

**Comment by sknorr** [comment]
https://www.youtube.com/watch?v=qLKhxjfG03A

**Comment by sknorr** [comment]
New round of proposals:

* SUSE Restricted DocBook
* DocBook for Lizards
* LizardDoc
* LizardDocumentation
* GeekoDoc

**Comment by tomschr** [comment]
Great! I like GeekoDoc.

Seems I have to keep the issues long enough in limbo to get good ideas. :smile:

**Comment by sknorr** [comment]
Started feature/geekodoc ... (not yet ready for a PR)
