### ISSUE TITLE
Support DTD and Structures for Vim for SUSEDoc

### ISSUE THREAD

**Issue by tomschr** [openSUSE/suse-xsl#233]
At the moment, the "official" schema for SUSEDoc is RELAX NG. We need:

* an inofficial DTD for backward compatible editing
* some Vim structures to help editing

@tbazant Please add some further links or files to this bug. :+1:

**Comment by tbazant** [comment]
Here is the dtd2vim script http://www.vim.org/scripts/download_script.php?src_id=5612 and here you can find how to install/use it: https://tbazant.github.io/vim/#id1841

**Comment by tomschr** [comment]
This issue was moved to openSUSE/geekodoc#3
