### ISSUE TITLE
Reduce content model of step

### ISSUE THREAD

**Issue by tomschr** [openSUSE/suse-xsl#234]
Content model of step should be reduced. ATM this isn't customized and too broad (for example, `bridgehead` shouldn't be allowed).

@taroth21 What do you would like to disallow (or allow) inside step?

**Comment by sknorr** [comment]
As discussed between Tanja and Toms, best idea would be to take possibilities Novdoc + assorted pre-approved extras (task...) as a baseline.

**Comment by tomschr** [comment]
See commit a7004481ab275574d8828aa1eadb8286624c7184

I've tried to remove procedures, bridgeheads etc.
