### ISSUE TITLE
Improve style of inline <literal/>

### ISSUE THREAD

**Issue by Vogtinator** [openSUSE/suse-xsl#241]
Usually, `<screen/>` is used for showing snippets. However, that does not work in paragraphs and needs a lot of vertical and horizontal space. The `<literal/>` tag is the next option, but looks too different from a screen. What about a smaller box displayed in-line with the text flow?

**Comment by sknorr** [comment]
We had something like this in HTML at one point. However, that was met with criticism for being too obtrusive iirc. Closing.

**Comment by Vogtinator** [comment]
That just that certain style that was used, there is probably a better one that can isn't as obtrusive

**Comment by sknorr** [comment]
Former code was this, feel free to improve in ways that make it less obtrusive:

```
code {
    border: 1px solid #D1D1D3;
    border-radius: 3px;
}
```

**Comment by janajaeger** [comment]
@tomschr this one is for you. Please decide how to proceed here.

**Comment by tomschr** [comment]
Thanks, but not relevant for our stylesheets.
