### ISSUE TITLE
Support performance="optional" in step

### ISSUE THREAD

**Issue by tomschr** [openSUSE/suse-xsl#245]
## Problem

Currently, the stylesheets doesn't detect the attribute `performance=optional` in a `step`. Any optional step is rendered the same, there is no optical distinction.
## Solution

For consistency reasons, it would be a good idea to render it the same. Suggestion would be to add a localized `(Optional)` in front of the first para (probably inline). Something like this:

```
Step 2: (Optional)  Check if everything is included in Wicked's configuration file: 
  [...]
```

**Comment by tomschr** [comment]
@jsetz11 This issue is something for you. :) Wanna try?

I've created checklists which could help to implement this feature.

### Common Checklist for PDF and HTML

This is the checklist which is the prerequisites that it works for FO/PDF and HTML:

* [ ] Create a new entry "step.optional" in a localization file. For English, start with the file `suse2013/common/l10n/en.xml`. The content could look like this:

   ```
<l:gentext key="step.optional" text=" (Optional)"/>
```

* [ ] Translate the entry for each language and insert it in their respective localization file. (I would recommend to do that as a last step when you have checked that your additions work as expected).

To insert the translated text, use the named template `gentext.template` like this:

   ```
<xsl:call-template name="gentext">
   <xsl:with-param name="key">step.optional</xsl:with-param>
</xsl:call-template>
```

The language is automatically retrieved by the `gentext` template.


### Checklist for FO/PDF


* [ ] For FO/PDF, open `suse2013/fo/lists.xsl` and go to template with matches `"procedure/step|substeps/step"`. This template is the one you need to extend.


### Checklist for XHTML

* [ ] Apply a similar approach to XHTML in `suse2013/xhtml/lists.xsl`. As there is no template that matches `"procedure/step|substeps/step"` (yet), you should copy the `step` template from the original file `$DBXSLT/xhtml/lists.xsl` and insert it into our stylesheet file.

---

Good luck! :+1:

**Comment by jsetz11** [comment]
Stylesheets now support `performance=optional` in `steps`.

Some localization files are not done yet. (ar, fi, hu,ja, no, sv, cs, ko, nl, pl, sh_cn, zh_tw, pt_br, lt_lt)

**Comment by sknorr** [comment]
Can you open a pull request from your branch? In the Github UI, click *Code* > *n branches* > *New pull request* next to [name of your branch].
