### ISSUE TITLE
Steps to install on Debian 8 (jessie)

### ISSUE THREAD

**Issue by tbazant** [openSUSE/suse-xsl#246]
This short procedure probably helps you fix possible issues for multi-distro support:

NOTE: i installed 'daps' first as described in https://github.com/openSUSE/daps/blob/master/INSTALL.adoc
1. Clone suse-xsl repo:
   `# git clone https://github.com/openSUSE/suse-xsl.git`
2. Install aspell-en:
   `# aptitude install aspell-en`
3. make symbolic links as debian has those files elswhere:
   `# sudo ln -s /usr/lib/aspell/en.dat /usr/share/aspell/en.dat`
   `# sudo ln -s /usr/lib/aspell/en_phonet.dat /usr/share/aspell/en_phonet.dat`
   `# sudo ln -s /usr/lib/aspell/en_affix.dat /usr/share/aspell/en_affix.dat`
4. run 'make'
   `# make`
5. <strike>fix VERSION:</strike> (unnecessary now)
   <strike>`# sudo ln -s /usr/share/xml/docbook/stylesheet/suse/VERSION /usr/share/xml/docbook/stylesheet/suse/VERSION.xsl`</strike>
6. run 'make install'
   `# sudo make install`

**Comment by sknorr** [comment]
Struck out (5.), because we now ship with both a  VERSION and a VERSION.xsl file.

**Comment by tomschr** [comment]
Seems to be something for a README.

@tbazant Could you check the steps if they are still correct/relevant etc.

**Comment by tbazant** [comment]
> Seems to be something for a README.
> 
> @tbazant Could you check the steps if they are still correct/relevant etc.

The above steps are working in Debian 11 now, unfortunately i dont have Jessie (8) any longer
