### ISSUE TITLE
Referencing Sections in a Chapter (PDF)

### ISSUE THREAD

**Issue by keichwa** [openSUSE/suse-xsl#249]
This is in the virtualization guide:

> For more information on the crashkernel parameter, see Book “System Analysis and
> Tuning Guide”, Chapter 17 “Kexec and Kdump”, Section 17.4 “Calculating crashkernel
> Allocation Size”.

I'd rather vote to get rid of the Chapter part ('Chapter 17 “Kexec and Kdump”,'). It is kind of redundant.

**Comment by sknorr** [comment]
Don't agree with that -- in the multi-page HTML version published on the Web, chapters are not numbered which means having information on the right section/part to look at can be very valuable.

**Comment by stefanq** [comment]
Appearance of links in PDF is already different as HTML links are rendered without page numbers.
Hence the appearance in PDF may just be further optimized.
Making only cross chapter links more verbose (i.e. render chapter number and/or title) may also be an option (this may also be optional by means of a customisation variable).

**Comment by sknorr** [comment]
True, for xrefs within a chapter, we probably could try to remove some junk. However, Karl's original bug report referred to an xref between multiple books. On the SUSE side, we there have the issue that we are (unfortunately) using another team's stylesheet for some of our output formats. And their output HTML does not contain section numbers...

**Comment by tomschr** [comment]
Stefan's comment in https://github.com/openSUSE/suse-xsl/issues/249#issuecomment-238599740 is right. This is the way that it should be. Closing.
