### ISSUE TITLE
Margin between para + simplelist is laarge

### ISSUE THREAD

**Issue by ghost** [openSUSE/suse-xsl#251]
See doc-sle/xml/sle_update_background.xml. There is a table containing entries such as:

```
       <para>
        11 SP3
       </para>
       <simplelist>
        <member><literal>&slsa;11-SP3-Pool</literal>
        </member>
        <member><literal>&slsa;11-SP3-Updates</literal>
        </member>
       </simplelist>
```

PDF output looks pretty bad because the paras have a very large bottom margin (or the simplelists have a very large top margin?).

**Comment by janajaeger** [comment]
This appears to be fixed in 2022. Closing for now. Feel free to reopen, if something fishy comes up again.
