### ISSUE TITLE
Missing output in PDF version of Daps User Guide

### ISSUE THREAD

**Issue by jsetz11** [openSUSE/suse-xsl#261]
DOC-DIR : DC-daps-user
XML-File : daps_user_trouble.xml
Chapter : Troubleshooting - Generating Output 
Problem : Answer won't show up in PDF - empty space
- but  works in HTML

**Comment by sknorr** [comment]
Not exactly sure what happened here but I can't see an issue (any more). Does sound a lot like an FOP error unfortunately.
