### ISSUE TITLE
Activate <?dbfo-need ...?> for FOP 2.1?

### ISSUE THREAD

**Issue by ghost** [openSUSE/suse-xsl#264]
Reported by fs: Tried dbfo-need PI & didn't have any success: 
`<?dbfo-need height="15em"?>`. Same issue exists with absolute values (i.e. units like mm or pt).

This is because the original stylesheets deactivate that functionality when FOP is detected. File: `fo/pi.xsl +937`

**Comment by tomschr** [comment]
This is true, but correct: the `dbfo-need` PI cannot be processed by FOP. ATM only XEP can detect that correctly. Unfortunately, this is a known deficiency by FOP and can only be solved in upstream FOP (Java):

Closing as invalid/wontfix.

**Comment by sknorr** [comment]
@tomschr, have you looked at whether this could work with FOP 2.1+?

**Comment by tomschr** [comment]
> have you looked at whether this could be enabled with FOP 2.1+?

According to the [Compliance](https://xmlgraphics.apache.org/fop/compliance.html#fo-object-block-container) page, the support is marked as *partial* for FOP 2.0 and FOP dev column. It seems, there hasn't been changed much. :disappointed: 

However, after browsing through the Web pages, I found the [whitespace management with fo:multi-switch](https://xmlgraphics.apache.org/fop/2.1/whitespacemanagement.html):

> [...] an extension for FOP’s page breaking algorithm that enables the handling of dynamic content. Dynamic content has multiple variants, only one of which will be inserted in the document. Variant selection is done in a First Come First Served manner and the first variant that fits within the remaining space in the current page is chosen. If no appropriate variant is found, the dynamic content will be skipped without affecting the rest of the document layout.

Probably nothing that really helps, but I thought, I add it to the records in case we want to implement this. Whatever it will look like.

**Comment by janajaeger** [comment]
@tomschr can we safely assume, things haven't changed and close this?

**Comment by tomschr** [comment]
Unfortunately, yes. I looked at the table again and support is still _partial_. So closing for the time being.
