### ISSUE TITLE
Stylesheet testing: linting of XSLT/HTML/CSS/FO/JS/EPUB

### ISSUE THREAD

**Issue by ghost** [openSUSE/suse-xsl#272]
Part of our stylesheet testing process should be the ability to lint input XSLT and also output to lint sample output documents (HTML/CSS/FO/JS/EPUB).

**Comment by sknorr** [comment]
Note to self: ESLint (written in Py***n) might help for JS...

**Comment by tomschr** [comment]
Don't understand the real issue. Not relevant anymore
