### ISSUE TITLE
Format Menuchoice properly in PDF ToCs

### ISSUE THREAD

**Issue by ghost** [openSUSE/suse-xsl#275]
This input:

```
<sect1>
<title><menuchoice><guimenu>System Details</guimenu><guimenu>Software</guimenu></menuchoice></title>
[...]
</sect1>
```

This output in the sidebar ToC of PDFs:

```
System DetailsSoftware
```

We should add a `>` character and spaces in between those here.

This is an issue in the SUSE Manager Reference Guide & looks ok elsewhere (afaict).

**Comment by janajaeger** [comment]
Couldn't confirm in 2022. Closing for now. Feel free to reopen, should this become an issue again.
