### ISSUE TITLE
Improve page counting (roman numerals before first chapter)

### ISSUE THREAD

**Issue by tomschr** [openSUSE/suse-xsl#283]
(This is coming from https://bugzilla.suse.com/show_bug.cgi?id=1010045)

Original problem:
> i was just confused when there was the, what i think is the page number(220), written next to the chapters name (Introduction). But when you then actually reach the Introduction you end up on page 236. 

One explanation:
> number 1 in the index in SES pdf starts on the 16th real page, the pages before bear no actual content and are numbered in rome numbers i, ii, iii etc

and

> your confusion comes probably from "different page numbers": one page number that is shown in the PDF and the other in the reader.

@sknorr: Do you see a solution here? Could we start with a (virtual) number 1 on the title page instead of roman numerals? Should we?

**Comment by sknorr** [comment]
Not sure -- there is probably a reason why tables of content do not count as normal content. I have not researched this, maybe there is a good reason.

Though, if we can help confused azubis... feel free to change (or set to wontfix).

**Comment by janajaeger** [comment]
This is pretty much standard (mis-)behavior of PDF readers. This is a won't fix.
