### ISSUE TITLE
alternatives/improvements to formatting as inline-blocks for commands etc.

### ISSUE THREAD

**Issue by ghost** [openSUSE/suse-xsl#284]
Tracker for https://bugzilla.suse.com/show_bug.cgi?id=1011620

Description by ke:
> lonely parens
> Inline elements such as systemitem or command(?) are problematic.  See attachment.
![lonely-paren](https://cloud.githubusercontent.com/assets/5476547/20527126/7a4a31e0-b0c7-11e6-8c94-b69c027c2209.png)

Comment 1 by sknorr:
>This is because this is an inline-block within in normal inline text. The inline-block breaks to the new line as a whole unlike a normal block which would in your example break either like:
>
>   (name/
>   value)
>  or like
>   (name
>   /value)
>
> The idea was that we should avoid such ugly breaks that might also induce people to add space where there should be none.
>
> Not sure this is fixable in a good way. I like the current compromise better than any other I can imagine right now.
>
> One (evil) way forward would be to also group punctuation around such elements into a inline-block. Besides not being trivial to implement, I am sure that would create other interesting issues, though.

**Comment by janajaeger** [comment]
This seems to be fixed. See bugzilla entry. Closing this for now. Feel free to reopen, should the problem persist.
