### ISSUE TITLE
Improve comments and/or fix logic in trim-verbatim (..?)

### ISSUE THREAD

**Issue by ghost** [openSUSE/suse-xsl#289]
Some of the logic in trim-verbatim seems overly dense now, to the point where I do not get anymore why something has happened. Investigate this.

- [ ] +32: xsl:when not(p-s::n()[s::* or n-s(s::t())]: Why is nbsp ignored here and norm-spa is used instead of translate?
- [ ] +45 to 60: first condition is clear but the others seem less explainable in hindsight.
- [ ] +56: Why compare string length when we could compare against empty string
- [ ] +89: xsl:when not(f-s::n()[s::* or n-s(s::t())]: Why is nbsp ignored here and norm-spa is used instead of translate?
- [ ] +115, +162: Consider a less dense default (=error) value than NONE

**Comment by janajaeger** [comment]
@tomschr if this goes beyond cosmetics, it might make sense to investigate this. But if the stuff does what it's supposed to or at least doesn't break anything, feel free to ignore and close.

**Comment by tomschr** [comment]
Don't understand that. Seems not relevant anymore.
