### ISSUE TITLE
missing l10n templates

### ISSUE THREAD

**Issue by ghost** [openSUSE/suse-xsl#294]
- [x] No template for "itemizedlist-label" (or any of its leaves) exists in the context named "styles" in the "zh_tw" localization.
- [x] object.xref.markup: empty xref template for linkend="app.naming" and @xrefstyle="select:number" (all langs, SLEHA Guide)

**Comment by janajaeger** [comment]
@tomschr still an issue in 2022?

**Comment by tomschr** [comment]
First item is already fixed. Second is a duplicate of #202
