### ISSUE TITLE
Guimenu separators (`>`) are green in the ToC

### ISSUE THREAD

**Issue by ghost** [openSUSE/suse-xsl#297]
- [ ] inline.xsl +581, when ancestor::title, we are applying green color to the separator. That generally makes sense but not in the context of a ToC.

- [ ] The separators are also entirely missing from intra-xrefs.

Not especially terrible right now, because nobody beside the SUMA people uses menuchoice all too often in titles.

**Comment by janajaeger** [comment]
The code is still unchanged in 2022. @tomschr, please decide how to proceed here.

**Comment by tomschr** [comment]
This is a writer's issue and bad style to use guimenu inside a title. Not relevant.
