### ISSUE TITLE
liberation-fonts vs liberation2-fonts Requires in suse-xsl-stylesheets

### ISSUE THREAD

**Issue by sknorr** [openSUSE/suse-xsl#298]
Copied from https://github.com/openSUSE/daps/issues/393, via zaitor:

> Currently suse-xsl-stylesheets "hard" Requires liberation-fonts, but with the current freetype2 we have in Tumbleweed (possibly even in Leap 42.2/SLE 12SP2, liberation2-fonts is the recommended font.
> Please consider changing this to suit the above.
> See https://www.freetype.org/freetype2/docs/subpixel-hinting.html
> This would not be an issue if liberation-fonts and liberation2-fonts conflicted each other, but they do, so we need to work around this in this package.
> Extrainfo: suse-xsl-stylesheets is the last package having a hard requires on liberation-fonts

**Comment by zaitor** [comment]
Hi Stefan

Isn't this if statement the exact opposite of what we want/need?
Sidenote: Is the Requires: Needed for openSUSE? Could we live with a Recommends for us there?

+# (openSUSE provides liberation2-fonts, while SLE is currently stuck on v1.)
 +%if 0%{?sles_version}
 +Requires:       liberation2-fonts
 +%else
  Requires:       liberation-fonts
 +%endif

**Comment by sknorr** [comment]
Yeah, I too realized (even through my delirium) that what I did yesterday does not really work and I'd have to redo this.

Luckily, both you and Dominique made proposals for a fix, so I don't need to ask around. I'll try [Dominique's fix](https://github.com/openSUSE/suse-xsl/commit/0779a0356324a27f3ec2de0a2cf67dce53507e4b#commitcomment-20809515) for now.

**Comment by andreasstieger** [comment]
This regresses in maintenance, see [boo#1044521](https://bugzilla.opensuse.org/show_bug.cgi?id=1044521).

**Comment by tomschr** [comment]
Has been fixed already by Stefan in [bsc#1080244](https://bugzilla.suse.com/show_bug.cgi?id=1080244).
