### ISSUE TITLE
Cross-refs with xrefstyle too small

### ISSUE THREAD

**Issue by ghost** [openSUSE/suse-xsl#300]
Since the recent text scaling updates, the text size of cross refs with xrefstyle is much too small. There must be some attribute missing that is used for normal xrefs.

Example from the Hitchhiker's Guide (I guess the context is not important here but provided anyway for historical accuracy):

```
  <itemizedlist>
   <listitem>
    <para>
     <xref linkend="sec.doc.infra.fate" xrefstyle="select:title"/>: the feature that...
    </para>
   </listitem>
  </itemizedlist>
```

**Comment by janajaeger** [comment]
Appears fixed in 2022. Closing this one.
