### ISSUE TITLE
xsl:attribute-set : use-attribute-sets recursion detected

### ISSUE THREAD

**Issue by ghost** [openSUSE/suse-xsl#301]
... during building PDF of the release notes with 2.0.7.1 (not quite sure which ones, I noticed during an rn-updater run).

**Comment by janajaeger** [comment]
@tomschr still an issue in 2022?

**Comment by tomschr** [comment]
Fixed in some xsltproc/libxslt release some time ago. Haven't seen this message. Not relevant anymore.
