### ISSUE TITLE
Rethink Numbering of Parts and Chapters

### ISSUE THREAD

**Issue by ghost** [openSUSE/suse-xsl#308]
Frank got a complaint from a customer who looked at the page for the first part trying to find the first chapter of the Security Guide because the structure is like this. He was unsuccessful and therefore a little confused, because the structure is like this:

```
1 First chapter
I First part
  2 Second chapter
  3 Third chapter
[...]
```

There are a number of thinkable solutions to this:

* restart the chapter numbering for every part (this would necessitate longer chapter numbers, e.g. I.3 etc.)
* if a book uses parts, make sure there are no un-part-ed chapters in it; alternatively, use no parts at all
* selectively hide some information about chapter numbers, e.g. on part overview pages
* do not number parts

Mind you, the customer went [to the documentation on suse.com/doc](https://www.suse.com/documentation/sles-12/book_security/data/part_auth.html) -- which we don't currently control. But we do have very similar issues in our own stylesheets

**Comment by tomschr** [comment]
At least, for the first item ("restart the chapter numbering for every part...") there is probably an easy solution: use the [`label.from.part`](http://docbook.sourceforge.net/release/xsl/current/doc/html/label.from.part.html) parameter.

**Comment by janajaeger** [comment]
No further info, no further complaints since 2017. Closing this for the time being.
