### ISSUE TITLE
PDF fails to build with saxon and the "ns" (DB5) stylesheets

### ISSUE THREAD

**Issue by fsundermeyer** [openSUSE/suse-xsl#31]
Error at xsl:stylesheet on line 20 of file:/usr/share/xml/docbook/stylesheet/suse2013-ns/fo/fo.xsl:
  Namespace prefix d has not been declared
Transformation failed: Failed to compile stylesheet. 1 error detected.
remake: *** [/data/git/doc-cloud/build/.tmp/susecloud-all-fop_color_en.fo] Error 2

**Comment by tomschr** [comment]
This is strange. The `fo/fo.xsl` doesn't use any DocBook elements at all. So no DB5 namespace is needed. I'm not sure why Saxon think it needs this namespace.

@fsundermeyer Could the Perl script the culprit?
