### ISSUE TITLE
Footnotes Support could be better

### ISSUE THREAD

**Issue by tomschr** [openSUSE/suse-xsl#314]
Currently, the footnotes have two issues:

* [x] Font size is too big
* [x] No footnote numbering

**Comment by sknorr** [comment]
fixed with 77cffd32fc1ec82181e215fe9e2f29b85b432dca 65a26c4d207a020cf58253031b4b0062a93bfa3c be24cf5726005d7412750ee6d1329b54fd6b725c

**Comment by tomschr** [comment]
Result is shown here:

![footnotes](https://cloud.githubusercontent.com/assets/1312925/26728221/c3cb51ea-47a9-11e7-90cb-4aeabb7d6c58.png)
