### ISSUE TITLE
Aspell word list should not be part of the stylesheets package

### ISSUE THREAD

**Issue by ghost** [openSUSE/suse-xsl#318]
The aspell dictionary really has nothing to do with the stylesheets. The only reason why we're still shipping this inside the stylesheet package is that it has always been that way...

- [ ] Create own repo
- [ ] Create own package
- [ ] Fix makefile in suse-xsl repo
- [ ] Remove aspell deps from suse-xsl.spec

**Comment by janajaeger** [comment]
Looks fixed in 2022
