### ISSUE TITLE
PDF bookmarks panel -  remove periods after part/section/appendix number

### ISSUE THREAD

**Issue by ghost** [openSUSE/suse-xsl#321]
Patrick reported this for some languages only zh-TW & zh-CN, but I think all languages have the issue that the PDF bookmarks titles look differently than our normal titles.

However, need to make doubly sure we get this right for Chinese, I think.

**Comment by tomschr** [comment]
Don't really understand the problem. No periods/dots in zh_cn and zh-tw.
