### ISSUE TITLE
handle format=PNG and format=png both

### ISSUE THREAD

**Issue by ghost** [openSUSE/suse-xsl#332]
It would be great not to need this fix (at least not for the capitalization):
https://github.com/openSUSE/geekodoc/issues/24

**Comment by tomschr** [comment]
It seems, the upstream stylesheets contain already some named templates which take into account different capitalization.

For example, `is.graphic.extension` in `xhtml/graphics.xsl` or `graphic.format.content-type` in `common/common.xsl`.

**Comment by janajaeger** [comment]
Related geekodoc issue is fixed. Therefore closing this as well. Feel free to reopen.
