### ISSUE TITLE
Montserrat font for headlines (?)

### ISSUE THREAD

**Issue by sknorr** [openSUSE/suse-xsl#335]
https://fonts.google.com/specimen/Montserrat

Montserrat looks similarly to our corporate but non-free headline font Gotham. Unfortunately, Montserrat has a somewhat limited set of characters (i.e. Europoean languages are fine, but there is no Greek and no Cyrillic). Evaluate if we can still use the font for something.

Font has a GH repo, might be more current than Google Fonts's version: https://github.com/JulietaUla/Montserrat

**Comment by tomschr** [comment]
See https://fonts.google.com/specimen/Montserrat for details.

**Comment by tomschr** [comment]
@sknorr The Montserrat fonts are available in OBS, [M17N:fonts](https://build.opensuse.org/package/show/M17N:fonts/google-montserrat-fonts).

**Comment by sknorr** [comment]
No longer relevant -- the SUSE branding has changed.
