### ISSUE TITLE
Wrong company name in PDF documentations

### ISSUE THREAD

**Issue by mschnitzer** [openSUSE/suse-xsl#34]
Hi,

if you create a PDF documentation with
```
daps -vv -d DC-SLE-RT-shielding pdf
```
the documentation contains a wrong company name:
```
SUSE Linux Products GmbH
```
I think this is a stylesheet problem.

**Comment by tomschr** [comment]
@mschnitzer Thanks. Where does it appear?

The only spot that I've identified is in `suse2013/fo/param.xsl` in parameter `company.address`. Do you mean that? If yes, just fix it to the right name. Other than that, I don't find any occurances.

Also look inside your XML code (`*.xml` *and* `*.ent`) just to be sure.

**Comment by mschnitzer** [comment]
You got an email with the PDF.

**Comment by mschnitzer** [comment]
@tomschr Thanks for fixing it :-)
