### ISSUE TITLE
Integrate hunspell and make aspell optional

### ISSUE THREAD

**Issue by tomschr** [openSUSE/suse-xsl#346]
Related to openSUSE/daps#422

The spec file needs to be adapted to remove aspell due to bsc#1052970. Some things to discuss:

* Do we want/need a subpackage just for aspell things? Magic doesn't like it as he sees "no benefit by creating a package containing a single file (the SUSE custom dictionary)".
* Should we create a separate repo just with our terms? Maybe with some make magic which can be used to create specific custom dictionaries?

**Comment by sknorr** [comment]
Hm, ... https://github.com/openSUSE/suse-doc-style-checker/pull/165 ?

**Comment by tomschr** [comment]
@sknorr Can we close this issue or is it still needed?

**Comment by sknorr** [comment]
We did not really switch yet, so far we only sidestepped the packaging issues. Not really sure -- do we have another issue actually tracking the progress of conversion to hunspell?

**Comment by sknorr** [comment]
Oh sorry -- just noticed that that was not the DAPS but the sxsl repo. Yes, let's close this here.
