### ISSUE TITLE
Build errors with DC-ses-admin, PDF-only

### ISSUE THREAD

**Issue by ghost** [openSUSE/suse-xsl#351]
We seem to generate an invalid FO file for DC-ses-admin @ f8e20f80e3c22e0b7c902357abc284d40637a68a .

Additionally, the book tries to intra-xref a step element (which does not work properly) -- not sure trying that is advisable. There is also a warning message about an attribute set recursion.

**Comment by janajaeger** [comment]
No more reports of his behaviour in the last four years, closing for now.
