### ISSUE TITLE
<simpara> is unsupported by suse-xsl

### ISSUE THREAD

**Issue by fsundermeyer** [openSUSE/suse-xsl#355]
asciidoc is generating <simpara> instead of <para> for adoc -> docbook conversions. When using the suse2013 stylesheets, <simpara> is rendered with green text in itemized lists.

I would expect <simpara> to be rendered the same way as <para> here.

**Comment by tomschr** [comment]
@fsundermeyer Is it HTML, PDF, or both?

This can be solved in different locations:

1. Configure ASCIIDoc/ASCIIDoctor
    This can be done by replacing all `simpara`s in `/etc/asciidoc/docbook45.conf` with `para`s.

1. A cleanup step
   Isn't that needed for the AD -> DB conversion anyway? In that case, we could use a simple XSLT clean up step which makes a `simpara` -> `para` conversion.

1. In our stylesheets
   Probably your preferred solution. :wink:

**Comment by sknorr** [comment]
Fixed already, forgot to close: https://github.com/openSUSE/suse-xsl/commit/ed9af3a2af99ec7f95025fce3d0ca8829be1385b
