### ISSUE TITLE
Unknown TOC element section

### ISSUE THREAD

**Issue by ghost** [openSUSE/suse-xsl#358]
I get error message in $subject when building the SLED release notes (commit bbb24d8), and the TOC comes out empty. However, this only happens with the non-namespaced styles. The -ns stylesheet does not seem to have an issue with this.
PDF only, it seems.

**Comment by tomschr** [comment]
@KucharczykL Do you still see this issues for your release notes? Please comment. :slightly_smiling_face:

**Comment by KucharczykL** [comment]
The original message doesn't provide enough information for me to properly check, but I've tried:

1. `git checkout bbb24d8`
2. `make single-html` and `make pdf`

No errors. TOC appears in both HTML and PDF.

Should I check something else?

**Comment by tomschr** [comment]
Thanks Lukas. :+1: No, that's all. I think, we can close it for the time being. Thanks for checking.
