### ISSUE TITLE
Fix Hard-Coded Bugzilla Link ("Report Bug")

### ISSUE THREAD

**Issue by tomschr** [openSUSE/suse-xsl#36]
In our HTML, each section (or title) contains a "Report Bug" link. At the moment, this points to Bugzilla. It would be nice, to make this customizable, for example, to link to GitHub.

At the moment, this file is responsible for that: [`suse2013/static/js/script.js`](https://github.com/openSUSE/suse-xsl/blob/develop/suse2013/static/js/script.js)

@jcayouette Is that good enough?

**Comment by jcayouette** [comment]
yes thanks I will run it by the team perhaps we can fix it quickly.

**Comment by tomschr** [comment]
@fsundermeyer Could you look into the JavaScript code and see if this is possible? Thanks!

**Comment by tomschr** [comment]
### Idea
A tracker URL shouldn't be hard-coded into the JavaScript code. Maybe we should integrate the tracker URL into our XML sources as meta information. Or we pass it as a parameter in our stylesheets that is set by daps.

Anyway, the variable `bugzillaURLprefix` has this code:

```javascript
var bugzillaURLprefix = 'https://bugzilla.suse.com/enter_bug.cgi?&product=' // ...
```

we should better replace it with a function that returns the complete tracker URL:

```javascript
var bugzillaURLprefix = extractTrackerURL(encodeURIComponent(bugzillaProduct), encodeURIComponent(bugzillaComponent));
```

The idea is, to add information about the tracker URL to our XML sources and transform it into a `<meta>` HTML tag. The JavaScript code could be extracted easily. If the tracker URL is not set, we could assume Bugzilla as default.

The advantage is we don't have any hard-coded URLs anymore and we are more flexible.

Don't know how to code this in JavaScript...

**Comment by mschnitzer** [comment]
GitHub supports the Query syntax in the URL too.

For example:
https://github.com/openSUSE/suse-xsl/issues/new?title=Beautiful%20Title&labels[]=bug&labels[]=Schema

**Comment by tomschr** [comment]
Ok, here is the current state:

1. Add the relevant tracker information into your XML source, preferably inside the `dm:docmanager` element (this is currently TBD and an issue for openSUSE/docmanager#56).
2. The `docbook.xsl` XSLT file extracts the respective `dm:docmanager`  elements and creates (X)HTML `<meta/>` elements, for example:
```html
<meta name="tracker-url" content="https://bugzilla.suse.com/enter_bug.cgi"/>
<meta name="tracker-bsc-product" content="SUSE Linux Enterprise High Availability Extension 12"/>
<meta name="tracker-bsc-assignee" content="tux@example.com"/>
```
3. The JS script `script.js` extracts the `<meta/>` information, assembles the tracker URL, and creates a link.
