### ISSUE TITLE
intra appendix has no en localization

### ISSUE THREAD

**Issue by ghost** [openSUSE/suse-xsl#361]
this seems fairly essential ..., i get:

```
No template for "intra-appendix" (or any of its leaves) exists in the context named "xref"
in the "en" localization.
```

**Comment by sknorr** [comment]
@cjschroder just noticed this ... we really want this fixed in the next version, since she's used an xref to an appendix now^^

**Comment by tomschr** [comment]
This is invalid, it works in suse2022 stylesheets (tested with DC-SLES-upgrade)
