### ISSUE TITLE
List title accumulates other titles

### ISSUE THREAD

**Issue by taroth21** [openSUSE/suse-xsl#365]
## Problem Description
In the Hitchhiker's Guide, stumbled across an itemizedlist with a title and formalparas inside the listitems. In PDF output, the titles of each formalpara within the list were accumulated and prepended to the list title. 

## Expected Behavior
Only the list title should appear as headline for the list.

**Comment by tomschr** [comment]
I've tried to reproduce it, but it works for the suse2022-ns stylesheets. Closing it.

<details>
  <summary>Screenshot and code</summary>

```xml
  <itemizedlist>
   <title>Hello World (list title)</title>
   <listitem>
    <formalpara>
     <title>AB</title>
     <para>The quick brown fox jumps over the lazy dog.</para>
    </formalpara>
   </listitem>
   <listitem>
    <formalpara>
     <title>CDE</title>
     <para>The quick brown fox jumps over the lazy dog.</para>
    </formalpara>
   </listitem>
  </itemizedlist>
```

![Screenshot_20220720_124205](https://user-images.githubusercontent.com/1312925/179963181-c0840892-1ea5-4d1a-bfca-2942eae6dba7.png)
</details>
