### ISSUE TITLE
Charis SIL has very wide + characters, looks weird when used in e.g. C++

### ISSUE THREAD

**Issue by sknorr** [openSUSE/suse-xsl#373]
Charis SIL has very wide `+` characters, looks weird when used in e.g. `C++`. 
It seems like the `+` character is optimized for use in math, not text. This makes it seem like there are extra unwanted spaces in the document.

**Comment by tomschr** [comment]
Well, maybe it's their SIL design?
I've used Fontforge to investigate further. I see in file `/usr/share/fonts/truetype/CharisSILR.ttf` the following "plus" signs:

* U+002B PLUS SIGN
* U+207A SUPERSCRIPT PLUS SIGN
* U+208A SUBSCRIPT PLUS SIGN

I've ignored the plus/minus signs; apart from the glyphs above, I can't see any dedicated mathematical plus sign.

(Setting it to lower priority)

**Comment by tomschr** [comment]
Some rendering from LibreOffice
![charissil-cpp](https://user-images.githubusercontent.com/1312925/44032241-da77affa-9f06-11e8-9cf4-185b0ac452e9.png)

**Comment by sknorr** [comment]
The question is more whether we should switch to a new font or whether we can request SIL to make changes (they have an ML for that, and they are responsive). I don't think downstream futzing with the font makes any sense.

**Comment by tomschr** [comment]
> The question is more whether we should switch to a new font or whether we can request SIL to make changes (they have an ML for that, and they are responsive)

Although the issue is ugly, we should try to fix that for upstream first. Switching to a new font has maybe other implications (apart from making typographical compromises).

**Comment by sknorr** [comment]
Let's close, I think I asked and they didn't want to do this.
