### ISSUE TITLE
Need a "line break" option in DocBook

### ISSUE THREAD

**Issue by chabowski** [openSUSE/suse-xsl#377]
Currently there is no option to add a line break to our DocBook documents. I realized that in certain cases it might be useful to add a line break. Is it possible to add an element for that? Or to add it somehow to the style sheet?

Line breaks for all output formats without having to "fake" via the screen element or so ...

**Comment by sknorr** [comment]
Could you give an example of the context?
If this is about regular paras, I guess `<simplelist type="vert"><member>First line</member><member>Second line</member></simplelist>` might work for you.

**Comment by chabowski** [comment]
Yes mainly for a space between two "regular" paras. Sometimes the "para" does not contain usual text but something else like a short example of something - and I want to be able to make this more visible via a blank line / extra space

**Comment by sknorr** [comment]
Ah, so not a line break but a blank line is what you want... Okay, that is different. I guess you could still try a simplelist with a single empty member between paras anyway. If you put that simplelist into an entity like `&emptyline;`, you would even save the excessive typing.

**Comment by chabowski** [comment]
Arggh I am sorry yes I mean a blank line - already confused myself ;-).

**Comment by chabowski** [comment]
Thanks Stefan - your proposal works, and there is now at least the option to add a blank line :-)

**Comment by sknorr** [comment]
Ok, closing this issue. (Will open a new issue for the underlying para spacing issues.
