### ISSUE TITLE
Overlong Titles in Best Practices

### ISSUE THREAD

**Issue by tomschr** [openSUSE/suse-xsl#382]
## Problem Description

For the Best Practices, overlong titles can break between words (which is not wanted).

## Expected Behavior

The title should have:

* no hyphenation between words
* the layout needs to be adapted

Reported by @chabowski

**Comment by sknorr** [comment]
> the layout needs to be adapted

What does that mean?

**Comment by tomschr** [comment]
> > 
> > * the layout needs to be adapted
> 
> What does that mean?

Well, Meike showed me a very, very long title. I'm not entirely sure anymore if we used any form of "fixed layout" (titles on a specific position), but it could mean, we need to work on the title page. Not more, not less.

**Comment by chabowski** [comment]
@sknorr: concerning the SBP, we have several issues regarding the title:
1.) The cover page seems to allow only titles with maximum 3 lines. "Thanks" to our long product names, this can become challenging. I hate long titles, but if you need to put the own product name AND a partner product name into an SBP title, the three lines to not suffice anymore.
2.) A word in the title should not be hyphenated. It happened with one of the last SAP papers, that the word "Linux" in the title was split over two lines into "Li-nux". Not good.

Unfortunately, for SBPs, we cannot always choose our own title, but need to take what we get from the author /partner ... So rules should probably be different for SBP
Hope that clarifies.

**Comment by janajaeger** [comment]
relates to #215 and #217

**Comment by tomschr** [comment]
Overlong titles needs to be adapted by writers. Stylesheets cannot fix this. Closing it as layout is already covered in the issues mentioned by Jana.
