### ISSUE TITLE
steps/list elements with figure as first element have display issues

### ISSUE THREAD

**Issue by ghost** [openSUSE/suse-xsl#383]
if the first element in a step is a figure, the ordinal number of the step is pushed down below that figure. this is not quite ideal but unfortunately also hard to fix, as this is based on default html behavior, afaict.

to fix, we need to display ordinal numbers via :before() rather than normally. that creates two issues:

* we lose support for older browsers (tbd which ones)
* we will likely introduce regressions, especially concerning nested procedures/lists

this was an issue in the caas platform documentation.

**Comment by janajaeger** [comment]
Let's make this a writing style issue rather than a stylesheet issue.
