### ISSUE TITLE
It's possible to put more content in tables than fits on PDF width

### ISSUE THREAD

**Issue by ghost** [openSUSE/suse-xsl#386]
v/ mnapp, https://github.com/openSUSE/daps/issues/507:

### Problem description

Content that is too long for table cells flows over the table cells

### Expected behavior

Content is handled with overflow controls to fit the available table (cell) width. Ideally a "fold to next line strategy to not lose visible content.

### Steps to reproduce the behavior

1. Create a table with long content
1. Export to PDF via DAPS

HTML via Asciidoctor:

![](https://user-images.githubusercontent.com/4920542/57538989-ca93c700-7349-11e9-8cfe-b5357432115a.png)

PDF via DAPS:

![](https://user-images.githubusercontent.com/4920542/57538990-ca93c700-7349-11e9-8067-3e9e8c1b625c.png)

**Comment by sknorr** [comment]
Mayvbe there is a way to enable completely random breaks in FOP by inserting 0-width spaces? Apparently, there is no equivalent of CSS's `word-break: break-all` property.

https://stackoverflow.com/questions/18317433

**Comment by sknorr** [comment]
We could also consider a warning message based on number of columns in a table. Anything 5+ columns always needs visual verification.

**Comment by tomschr** [comment]
Writers are responsible for their tables. Non-issue, closing.
