### ISSUE TITLE
Stylesheets ignore table centering in PDF

### ISSUE THREAD

**Issue by sknorr** [openSUSE/suse-xsl#387]
v/ mnapp, https://github.com/openSUSE/daps/issues/506:

### Problem description

Asciidoc allows values in table cells to be positioned (left, center, right). This positioning is ignored.

### Expected behavior

Content formatting is honored by the converter and properly formatted in the output.

### Steps to reproduce the behavior

- Configure a table with aligned cell contents
- Convert to PDF with DAPS

```
==== Certificate keys
v/ mnapp, https://github.com/openSUSE/daps/issues/506:


[options="header",cols="<,^,^"]
|===
|Path                         |Key type |Key length (bits)
|apiserver.key                |RSA      |2048
|apiserver-kubelet-client.key |RSA      |2048
|apiserver-etcd-client.key    |RSA      |2048
|etcd/server.key              |RSA      |2048
|etcd/healthcheck-client.key  |RSA      |2048
|etcd/peer.key                |RSA      |2048
|===
```

# HTML from AsciiDoctor
![Screenshot_20190510_173026](https://user-images.githubusercontent.com/4920542/57538777-683ac680-7349-11e9-8f96-dcf72a8fce9b.png)

# PDF from DAPS
![Screenshot_20190510_172806](https://user-images.githubusercontent.com/4920542/57538688-417c9000-7349-11e9-9d3e-d247bf3ab8d6.png)

**Comment by tomschr** [comment]
Hmn, I cannot really reproduce this. I used this on a openSUSE 15.0 system:

* Current version of the stylesheets (`git describe` => `2.0.8-52-gd1d5563`) of the `opensuse/suse-xsl` repo.
* daps-3.0.0-lp150.152.1.noarch
* ruby2.5-rubygem-asciidoctor-1.5.6.1-lp150.1.2.x86_64
* xmlgraphics-fop-2.1-lp150.4.1.noarch
* docbook5-xsl-stylesheets-1.79.2-lp150.6.1.noarch

I looked a bit deeper and found this:

* Transforming the AD input into DocBook reveals, that the `<entry>` elements contain the correct `align="..."` attributes. From the view of the source code, this is correct.
* Looking into our SUSE stylesheets, we have the file `fo/table.xsl` but no equivalent for HTML.
* The `fo/table.xsl` only customizes the header, but no other template.

Our SUSE FO stylesheets don't have any code that customizes tables (apart from the above minor change). That means, they rely on the DocBook stylesheets.

Closing this for the time being as WORKSFORME. If you think, this is still relevant, reopen it.
