### ISSUE TITLE
PDF: Building with --draft does not insert DRAFT watermark

### ISSUE THREAD

**Issue by taroth21** [openSUSE/suse-xsl#389]
## Problem Description
```daps -d DC-SLES-deployment pdf --rootid=cha.boot_parameters --draft``` did not result in a DRAFT watermark in the PDF. Only when using
```daps -d DC-SLES-deployment pdf --rootid=cha.boot_parameters --remarks``` I saw a DRAFT watermark in the PDF. 

## Expected Behaviour
Building PDFs with --draft should insert DRAFT watermark.

**Comment by janajaeger** [comment]
Fixed.
