### ISSUE TITLE
Investigate SASS/LESS

### ISSUE THREAD

**Issue by tomschr** [openSUSE/suse-xsl#39]
## Current Issue

Maintaining CSS can be tedious and error-prune.
## Idea

Maintaining our CSS with SASS (Syntactically Awesome Stylesheets) could make life a bit easier. SASS is a preprocessor and compiles a SASS script into CSS. SASS supports variables, mixins (kind of functions), and more.
## Further Information
- http://sass-lang.com
- GitHub repo: https://github.com/sass/sass
- openSUSE package: `rubygem-sass`

**Comment by sknorr** [comment]
Why close this? Using SASS or LESS would seem like a good enhancement. Especially, if we want to keep multiple documentation brandings around (SUSE, OpenSUSE, DAPS).

LESS
-------

*Pros*

* CSS-compatible -> we could start using it by adding a preprocessor, and then go from there

*Cons*

* Syntax is more error-prone
* A little less powerful

SASS/SCSS
---------------

*Pros*

* Nicer syntax

*Cons*

* Can't start using it right away, as the syntax is different from CSS

**Comment by tomschr** [comment]
This is already in place for the suse2022-ns variant.
