### ISSUE TITLE
authorgroups come out without email

### ISSUE THREAD

**Issue by ghost** [openSUSE/suse-xsl#390]
This affects both HTML and PDF, we don't display the e-mail address from this structure in the info element:

```
<authorgroup>
<author>
<personname>
<firstname>Ich</firstname>
<surname>Mich</surname>
</personname>
<email>blu@blub.se</email>
</author>
<author>
<personname>
<firstname>Ich</firstname>
<surname>Du</surname>
</personname>
<email>dein@ma.in</email>
</author>
</authorgroup>
```

**Comment by tomschr** [comment]
If I'm not mistaken, this was a design design looong time ago. Do we really want to expose our mail addresses to spamers? :thinking: 

I guess this is coming from the ASCIIDoc front, so I'd suggest to add a parameter to adjust it, so we could satisfy both worlds. Would that work?

**Comment by sknorr** [comment]
My guess was that this was not a design decision but that I coded for DocBook 4 at the time and the tags changed since. Who knows...

And if you put in your e-mail address, I guess you want it published as well, no?

**Comment by tomschr** [comment]
> My guess was that this was not a design decision but that I coded for DocBook 4 at the time and the tags changed since. Who knows...

Actually, there was a change for DocBook 5: you need to put `firstname` and `surename` into `personname`. So one more element. In DocBook 4 you didn't need this.

However, that didn't have any influence. Our stylesheets use the `person.name` template which takes care of extracting the author(s).

Just for the records: The template for processing authors is `add.authorgroup` in the file `suse2013/xhtml/titlepage.templates.xsl`.

> And if you put in your e-mail address, I guess you want it published as well, no?

Personally, I try to limit it.
Apart from that, it's meta information in DocBook. Meta information is not guaranteed to be published.

**Comment by tomschr** [comment]
Non-issue. Only for the SBP stylesheets this could be relevant (which is already covered).
