### ISSUE TITLE
xref / intra-xref detection is incorrect when the root ID is not a book or article

### ISSUE THREAD

**Issue by ghost** [openSUSE/suse-xsl#391]
(this bug is one to test later on, I am not completely sure it is valid)

It seems we only detect xrefs as intra-xref when they point to another book or article. However, when you build an individual chapter, we don't detect that xrefs outside of that chapter need to be displayed as unclickable intra-xrefs.

**Comment by janajaeger** [comment]
@tomschr can you shed some light on this?

**Comment by tomschr** [comment]
Non-issue. The intra-xrefs detects the target _inside_ another book, article, etc.
