### ISSUE TITLE
zh_CN, zh_TW, ko_KR: Missing characters in fonts

### ISSUE THREAD

**Issue by ghost** [openSUSE/suse-xsl#393]
Reports Padraig:
> * The Chinese fonts do not support the non-breaking hyphen character fully. The hyphen doesn’t break but it renders as a corrupted character.
> * The Korean fonts do not support the non-breaking space character. It renders as a # character. This was reported in June 2018 also. (Patrick did not update his version of DAPS to check if it had been resolved, for fear of breaking something else 😊)

**Comment by tomschr** [comment]
Already covered in #505
