### ISSUE TITLE
ar: BiDi markers are visible

### ISSUE THREAD

**Issue by ghost** [openSUSE/suse-xsl#394]
Reports Padraig:
> The bi-di LRM (LEFT RIGHT MARK), and perhaps others, render in the Arabic file. They should be invisible. We used XEP for Arabic. For example, search for ‘AWS’ in the SLES InstallQuick, and notice the little up arrow to the right of the close-parentheses.

**Comment by tomschr** [comment]
Seems not relevant anymore.
