### ISSUE TITLE
Allow to disable intra book links

### ISSUE THREAD

**Issue by tomschr** [openSUSE/suse-xsl#398]
## Problem Description

(reported by @dmpop)

Using an `<xref/>` from one book into another we have the term "intra-xrefs". Usually, these intra-xrefs have the form "BookTitle ChapterTitle [...]".

However, sometimes we want to customize the output of these intra-xrefs, for example, to have only the title. This is currently not possible as "intra-xrefs" don't allow to be customized.

## Proposed Solution

To disallow intra-xref for a specific  `<xref/>`, we could use the `role` attribute. With the value of `no-intra` we disable that.

There are these options:

* Using `<xref linkend="another-id-in-a-book"/>` creates the usual output.
* Using `<xref linkend="another-id-in-a-book" role="no-intra"/>`, disables intra-xrefs and creates the normal xref output.
* Using `<xref linkend="another-id-in-a-book" role="no-intra" xrefstyle="select:title"/>`, disables intra-xrefs, fall back to normal xref and only output the title.

---

**Update**
It seems, we don't need the `@role` attribute. If we really want to disable/avoid these intra-xrefs, there is a better approach: use the `xrefstyle` attribute.

**Comment by sknorr** [comment]
For another approach to fixing this issue, see: #226.

**Comment by tomschr** [comment]
It seems, it works! 

This code:

```xml
<variablelist>
  <varlistentry>
   <term><xref linkend="bla"/></term>
   <listitem>
    <para>Normal Intra-xref</para>
   </listitem>
  </varlistentry>
  <varlistentry>
   <term><xref linkend="bla" xrefstyle="template:%n %t"/></term>
   <listitem>
    <para>with xrefstyle="template:%n %t"</para>
   </listitem>
  </varlistentry>
  <varlistentry>
   <term><xref linkend="bla" xrefstyle="select:label quotedtitle"/></term>
   <listitem>
    <para>with xrefstyle="select:label quotedtitle"</para>
   </listitem>
  </varlistentry>
</variablelist>
```

Creates this output:

![Screenshot_20191016_131935](https://user-images.githubusercontent.com/1312925/66914921-1abd3680-f018-11e9-848b-c8e6fd15d32a.png)
