### ISSUE TITLE
Avoid sect1s from starting on the lower third of a page

### ISSUE THREAD

**Issue by ghost** [openSUSE/suse-xsl#401]
Right now, our PDF stylesheets often start sect1 on the lower third of a page instead of pushing that content to the next page. That is really ugly. So I was wondering whether the trick of setting a large bottom padding (= regular bottom padding + (1/3 A4 - bottom page border)) and a negative margin (= - (1/3 A4 - bottom page border)) would help matters here.

**Comment by janajaeger** [comment]
Probably no way to implement this in the short/mid term. Closing for now.
