### ISSUE TITLE
Old doc homepage still listed in PDF

### ISSUE THREAD

**Issue by taroth21** [openSUSE/suse-xsl#402]
Page 2 of our PDFs still list the old doc homepage (https://www.suse.com/documentation):

```
Publication Date: November 22, 2019
SUSE LLC
10 Canal Park Drive
Suite 200
Cambridge MA 02141
USA
https://www.suse.com/documentation
```

Please replace with ```https://documentation.suse.com/``` and publish the update stylesheet as RPM package.

**Comment by tomschr** [comment]
Good catch! Thanks Tanja!

**Comment by tomschr** [comment]
@taroth21 I've prepared a `release/2.0.15` branch and will build a RPM next week. :wink:

**Comment by taroth21** [comment]
To prioritize the package in the maintenance queue, use:
$ iosc rq priorize -m '$your_reason' $request_id important

**Comment by tomschr** [comment]
Created submit request for openSUSE Factory: https://build.opensuse.org/request/show/750917
