### ISSUE TITLE
Product number should always be visible

### ISSUE THREAD

**Issue by taroth21** [openSUSE/suse-xsl#408]
Based on the feedback in https://bugzilla.suse.com/show_bug.cgi?id=1152504#c14, we maybe should discuss if to only mention the product number in the source code if really needed.

However, if the product number is only rarely mentioned in the text, it is even more important that each HTML and PDF page of the documentation state which product version the document applies to. For PDF, the current layout gives the product abbreviation and version number in the footer, so this is OK.

But in HTML and single-page HTML, the readers do not necessarily see at first sight which product version the document refers to (they have to scroll up). This should be changed, because every page can be page one.

**Comment by sknorr** [comment]
Fixed for desktop window widths in the suse2022-ns stylesheets. Keeping the version number visible at all times at lower window widths is less feasible because of space constraints.

Still not fixed in older stylesheets. Closing nonetheless.
