### ISSUE TITLE
translation feedback Feb 2020: ja -- margin improvements

### ISSUE THREAD

**Issue by ghost** [openSUSE/suse-xsl#414]
ja

- [ ] formatting needs to be fixed - indented more. qandaset/
qandaentry/question/para.
- [ ] The full-stop at the end of the paragraph numbering is being overlaid. See SES 6 JA Storage Admin, page 194, section 15.6.
- [ ] More space between lines. See warning/title. See the Warning on 
[which book?] page 173 in section 12.9.

Assuming all of these are PDF issues

**Comment by janajaeger** [comment]
Most of these are implemented with the 2022 stylesheets. The qandaset issue has been reported in #12 - we added ja there :) Closing for now.
