### ISSUE TITLE
language feedback Feb 2020: section labeling in PDF TOC & date format

### ISSUE THREAD

**Issue by ghost** [openSUSE/suse-xsl#415]
zh-tw

- [ ] In the PDF bookmark, "章 n." should be changed to "第 n 章". For 
example, "章 1." should be changed to "第 1 章". And the period following the 
chapter number and section number should be deleted. 
- [ ] The date format needs to be modified. 2020-2-18 (Y-m-d). We 
tried to fix it in the L10n file for zh_TW. It did not work. Perhaps it needs 
to be also updated in the nwalshe5 L10n file.

**Comment by janajaeger** [comment]
@jfaltenbacher is this one still relevant?

**Comment by janajaeger** [comment]
Checked with current 15 SP4. Looks fixed. Closing for now.
