### ISSUE TITLE
Old issues from Trello

### ISSUE THREAD

**Issue by ghost** [openSUSE/suse-xsl#416]
These probably need to de-duped with stuff already reported here and stuff that is already fixed. This is just a quick dump, so I can close the old Trello board.

- [x] ~"verbatim" areas: FOP hyphenates before many special characters, like :/ -|"]} – no matter where they are on the line (See e.g. "Example 5.3.  Pretty-printed Output ..." in the DAPS User Guide) DocBook-FO parameter hyphenate.verbatim.characters might be relevant. (see: http://sourceforge.net/p/daps/tickets/135/ )~
- [x] ~Try to avoid breaks within e.g. parameters (--\ pretty, etc.) - Maybe add 0-width non-breakable spaces? Maybe add policy of limiting lines in screens to 80 characters.~

Possibly upstreamable:

- [x] HTML: add $homepage + $logo-image parameter to link back to company homepage
- [x] ~HTML: role=legal should add class to elements, would allow better CSS to target licenses~
- [x] ~FO: ToC of books/articles not listed in PDF bookmarks - This bug only appears when we only build a book/article that is contained in a set. It works for books that are not part of sets and of course for the set itself.~
- [x] ~HTML/FO: getting title and and outline number separately is not as it should be. Relevant for our re-jiggering of titles from eg.`A. Appendix → <grey>A</grey> <green>Appendix</green>`~
- [x] ~HTML/FO: adding productname/productnumber to title page??~
- [x] ~HTML/FO: xrefs to other books~
- [x] ~HTML/FO: remove hardcoded bold/italic text and let this depend on parameter - It would be even cooler if you could subtly sneak in separate bold/semi-bold toggles for the different types of fonts (body.font.family, dingbat.font.family,sans.font.family title.font.family,monospace.font.family) … that last part is clearly a pipe dream and not too useful for upstream, I suppose.~
- [x] HTML: graphical.admonition markup looks pretty shoddy
- [x] ~HTML: upstream screen-wrap?~
- [x] ~HTML/FO: Localise draft image (use up to 10 characters from gentext:"Draft" for the current language) (draft page masters currently use fo-external-image; to realise this idea, I would need to be able to use an instream-foreign-object; so this would necessitate replacing every single draft master page, doing it upstream might be the only sane option – so not doing this for now)~

**Comment by janajaeger** [comment]
As most of this is already implemented or deprecated in 2022, we close this one :)
