### ISSUE TITLE
Increase para margins in lists

### ISSUE THREAD

**Issue by ghost** [openSUSE/suse-xsl#418]
Paragraph margins within (variable-) lists are pretty tight, making it a bit hard to see where paragraphs end.

HTML:
![HTML](https://user-images.githubusercontent.com/5476547/77564073-742c6a00-6ec2-11ea-9bac-70f960a1c3f4.png)

PDF:
![PDF](https://user-images.githubusercontent.com/5476547/77564079-755d9700-6ec2-11ea-8d33-ecaeb60e7ea1.png)

v/ @cjschroder

**Comment by janajaeger** [comment]
This seems to have been fixed. Para margins look no different in lists than they look elsewhere. Closing this.
