### ISSUE TITLE
SUSE Branding: Integrate New Color Palette

### ISSUE THREAD

**Issue by tomschr** [openSUSE/suse-xsl#419]
## Problem Description

SUSE has got a new brand and with such a new color palette.

![ACL_Color](https://user-images.githubusercontent.com/1312925/78867534-8b7e6200-7a41-11ea-9708-2a1521b8d3f5.jpg)

## Expected Behaviour

New colors available in HTML and PDF.

## References

https://one.suse.com/content/perma?id=20088

**Comment by sknorr** [comment]
This is the 2020 palette that we never implemented in the end, as it was superseded by the 2021 palette. The 2021 palette is now in use for the suse2021 stylesheets.
