### ISSUE TITLE
Table of contents lacks sect1 sections if part of a preface

### ISSUE THREAD

**Issue by cwickert** [openSUSE/suse-xsl#425]
## Problem Description

In the context of the recent discussions about the preface "About this Guide", I stumbled across the following bug: Currently the table of contents in PDFs only lists `<sec2>`s inside `<preface>`s, not `<sec1>`. This is inconsistent with the structure and very confusing. One cannot understand the title of a section without the context of the section it's part of.

![Screenshot of the Admin Guide:](https://i.ibb.co/XFnmjZv/Screenshot-Admin-Guide.png)

As you can see, the outline on the right lists all sections inside of the preface, while the TOC only lists the `<sec2>`s.

The problem only affects preface. If you change it to `<chapter>`, everything is fine.

## Expected Behaviour

TOC and outline should be consistent. All `<sec1>`s and `<sec2>`s should show up in the TOC. Basically the TOC part of the `<preface>` should look the same as for other `<chapter>`s

**Comment by tomschr** [comment]
This is clearly a bug. Thanks for the report, Christoph.

Actually when I've implemented it, my idea was to scrub all sections and subsections from preface. Only the preface title should appear in the TOC. Mostly as prefaces doesn't convey that much information. The TOC also gets a bit smaller if we don't show the information.

Something like in the screenshot below:

![Screenshot_20210203_191905](https://user-images.githubusercontent.com/1312925/106791073-bed75080-6654-11eb-98c4-145d788e64ee.png)

**Comment by tomschr** [comment]
@cwickert I've created the branch `bugfix/425-toc` so you can have a look.

**Comment by tomschr** [comment]
Here is another attempt to compare it with https://github.com/openSUSE/suse-xsl/issues/425#issuecomment-772720047

![Screenshot_20210204_163725](https://user-images.githubusercontent.com/1312925/106916307-4d0c0f00-6707-11eb-84ab-ecb43d9efa7c.png)
