### ISSUE TITLE
Add Bug Tracker Links to DocBook 4 HTML Output Again

### ISSUE THREAD

**Issue by tomschr** [openSUSE/suse-xsl#43]
Bug tracker information is tracked in DocManager. However, this is only possible for DocBook5. For DocBook4, this is not possible as we need to add these elements into Novdoc schema (which we would like to avoid).

One way to do it is to add the following PI **before** the root element:

```xml
<?suse-bugtracker url="https://bugzilla.suse.com/enter_bug.cgi"
                  product="SUSE Linux Enterprise Server 12 in Public Clouds"
                  component="Other"
?>
```

The pseudo-attributes (`url`, `product`, etc.) mean the same as the DM elements (`dm:url`, `dm:product`, etc.)

The stylesheet first searches for DM elements in the DM namespace `urn:x-suse:ns:docmanager`. If it cannot find a bugtracker URL, it falls back to searching for the above PI.

**Comment by tomschr** [comment]
Probably the easiest way is to extend the file `suse2013/xhtml/tracker.meta.xsl` with the above PI.

**Comment by sknorr** [comment]
This is now implemented with the following syntax:
Within the `<info/>`/`<(chapter|set|article|...)info/> element, add

```
<?dbsuse-bugtracker url="..."?>
```

The `url` "attribute" is always mandatory, additionally there are available:

* bsc/GitHub: assignee
* bsc: component
* bsc: product
* bsc: version
* GitHub: labels

Note that the PI always needs to have all desiredattributes within it. With the DocManager version, you can set a URL and an assignee at e.g. the `set` level and then override the assignee at the `book` level.

**Comment by sknorr** [comment]
This is already documented in the GitLab howto...
