### ISSUE TITLE
Charis SIL 6.x is incompatible with FOP

### ISSUE THREAD

**Issue by sknorr** [openSUSE/suse-xsl#438]
Within the suse2013 and suse2021-ns stylesheets, we're using Charis SIL as a font for paragraphs in PDFs. This has always worked fine, however, version 6.x of the font, which since mid-Aug 2021 has been shipped via M17n:fonts is incompatible with FOP. The incompatibility shows in the sense that the font can't be embedded into the document for some reason, though on systems with the font installed, the PDF will usually appear correctly. To determine whether a PDF is broken, you can

* check the font properties window of your PDF reader
* open in Firefox's pdf.js embedded viewer which will switch to a default font.

For the moment, that is fine because we can just switch back to a working 5.x version (as shipped in Leap up to 15.3 by default) in every context that matters. We will also need to migrate suse2021 to the Poppins font eventually (but of course that font has issues with FOP as well--FOP always selects the ultra-light version rather than the regular one).

**Comment by sknorr** [comment]
The Poppins issue could probably be dealt with just a custom package with only a limited number of weights. I.e. just regular+bold (and italics of both). The issue is mostly that FOP can't deal with 100, 200, 300, ... weights properly somehow.

**Comment by tomschr** [comment]
> The Poppins issue could probably be dealt with just a custom package with only a limited number of weights. I.e. just regular+bold (and italics of both). 

I would advise against this. Although a custom package would probably technically work, it's something "separate". See my idea below.

To meet our requirements, I would suggest a different approach. I have these ideas in mind:

a. Create a new directory, lets say `/usr/share/daps/fonts/`, and *link* only the fonts that you need from the original `/usr/share/fonts/truetype/`. Additionally, add the first directory into the FOP configuration to be searched for fonts. This may help to exclude the "wrong" fonts files so FOP does only find what are available.
Maybe we could insert these links into the suse-xsl-stylesheets package. I think, it would be an appropriate place as we need font dependencies anyway.

- or -

b. Register only those fonts in FOP that are really needed (see link in https://github.com/openSUSE/suse-xsl/issues/438#issuecomment-911317423).
    I'm not entirely sure if this would solve the issue, but it could be worth a try.

Would suggest that we create a small FO file and test the Poppins font. We could combine that with the Charis font(s) as we need to test them too. So we could do that in one go.

I'm also surprised about the changes in Charis. If our test wasn't successful we might need to either a) stick to version 5 or b) get help from FontForge and re-export the font to TTF again. That could (hopefully) solve the problem. Whatever it might be.

**Comment by sknorr** [comment]
> b. Register only those fonts in FOP that are really needed (see link in #438 (comment)).

I have been talking to Frank about the need for per-stylesheet FOP and XEP config files before, but so far that is not implemented. The XEP and FOP config cannot be determined via the stylesheet. It follows the usual 1. DC file - 2. ~/.config/daps/dapsrc - 3. /etc/daps/dapsrc precedence rule. For us, this is not particularly useful.

**Comment by sknorr** [comment]
@tomschr I promised to add my (broken!) FOP patch here, attempting to work out the issues with Work Sans & Poppins, this is it: [0001-Fix-detection-for-thin-extra-light-black-fonts.patch](https://github.com/openSUSE/suse-xsl/files/7179954/0001-Fix-detection-for-thin-extra-light-black-fonts.log)

**Comment by quatran** [comment]
Issue can't be longer reproduced. It was probably fixed by an update for `xmlgraphics-fop`.

**Comment by quatran** [comment]
I have opened an Apache Jira Ticket for the issue regarding Poppins

https://issues.apache.org/jira/browse/FOP-3045

**Comment by sknorr** [comment]
Ok, since the Charis issue is reportedly solved but the Poppins/Work Sans issue is still open, I guess, we need a new bug.
Welcome, #446..

**Comment by sknorr** [comment]
I finally got to checking this again. It appears the issue is fixed by FOP 2.6.

We are not using either FOP 2.6 or Charis 6.0 in our Leap containers but we probably should ...
