### ISSUE TITLE
Co-branding of title pages

### ISSUE THREAD

**Issue by ghost** [openSUSE/suse-xsl#448]
We need to be able to put multiple company logos on PDF title pages and at the beginning of HTMLs. The old suse2013-sbp layout has support for using `article/info/cover` elements to do that, we need to add that support to the ~suse2021~ suse2022 stylesheets and extend it to support HTML too.

Relevant for https://github.com/doc-suse-com/site/issues/53.

cf. #215.

**Comment by tomschr** [comment]
This is already taken into account in #507.
