### ISSUE TITLE
Implement green color for checkmarks in support matrix tables

### ISSUE THREAD

**Issue by tbazant** [openSUSE/suse-xsl#453]
## Problem Description
While the UTF crossmark is naturally red, checkmark is normally black and is not so distinct. Greening it would help readability

**Comment by tomschr** [comment]
I've implemented now the colored text in the above PR.

Basically you need a processing instruction `<?dbsuse color="..."?>` wrapped inside a `<phrase>`. The `color` key can hold several possible values:

* SUSE brand colors
  suse-jungle-green, suse-pine-green, suse-midnight-blue, suse-waterhole-blue, suse-mint, suse-persimmon, suse-fog
* "Typical" CSS color names
  aqua, black, blue, darkgray/darkgrey, fuchsia, gray/grey, green, lime, maroon, navy, olive, orange, purple, red, teal, white, yellow
* RGB colors
  with the syntax #RRGGBB (wheres R, G, and B are a single hex digit)

---

If you want to try this out, here is a small procedure:

1. Clone the `openSUSE/suse-xsl repo`.
2. Switch to the `453-color-para_phrase` branch.
3. Run `daps` with the `--styleroot` option. Replace `$PATH_TO_CLONED_DIR` with the directory from step 1.

       daps --styleroot=$PATH_TO_CLONED_DIR/suse2022-ns/ ...
