### ISSUE TITLE
Disable alternate row coloring for two-column informaltables

### ISSUE THREAD

**Issue by janajaeger** [openSUSE/suse-xsl#462]
Currently, the default for all tables even informal ones is to have alternate row coloring to improve readability. This option, should be turned off for two-column informaltables as they normally consist of a first column listing some sort of key and a second column that lists a value or description.

In this case, it would make sense to either:

- use a proper table with a heading and keep the coloring
- let the stylesheets color the first column as they would with a heading and ditch the coloring for the alternate rows and go with a plain white background for the entire thing

An example which triggered this issue can be found here:
https://documentation.suse.com/sles/15-SP4/html/SLES-all/cha-virt-support.html#id-1.12.3.8.5.6.3

**Comment by janajaeger** [comment]
Third alternative brought up by Tahlia: Ditch those use cases altogether and use lists instead. This would make this issue a style issue rather than a stylesheet issue. Feel free to close as invalid.

**Comment by tomschr** [comment]
I would lean toward Tahlia's idea and make it a styleguide issue rather than a stylesheet. I'm closing it as invalid (as you suggested), but feel free to reopen it.
