### ISSUE TITLE
Use colon (":") by default at the end of formalpara titles

### ISSUE THREAD

**Issue by sknorr** [openSUSE/suse-xsl#47]
Normally, formalparas use dots (".") at the end of the title.
We also have some documentation that (inconsistently) uses colons at the end of formalpara titles (e. g. apps_evolution.xml).

```
<formalpara>
  <title>Something:</title>
  <para>Something something.</para>
</formalpara>
```

 However, I almost think it would make sense to use colons as the default. And it should be easy too, toms remembered that there was some kind of parameter.

**Comment by tomschr** [comment]
I looked it up and it's the [`runinhead.title.end.punct`](http://docbook.sourceforge.net/release/xsl/current/doc/fo/runinhead.title.end.punct.html) parameter.

**Comment by sknorr** [comment]
Maybe, since (I think) we already have special casing for Chinese here, we should create a custom gentext context ..?

**Comment by tomschr** [comment]
Agree with you, good idea.  I'll do it.
