### ISSUE TITLE
Use alt and title attributes with any kind of image in HTML

### ISSUE THREAD

**Issue by janajaeger** [openSUSE/suse-xsl#474]
Currently, alt values are in the HTML code, but not displayed by default by any browser. 

To get this information to show, modify the style sheets to duplicate the description or title values to produce both an `alt` attribute (Google expects this for SEO) and a title attribute (that actually gets displayed).

Also, consider adding them to informaltables and the like. Will try to come up with a list of requirements here.

**Comment by tomschr** [comment]
This was fixed in PR #481, so closing.
