### ISSUE TITLE
"Edit source document": Auto-generated links generate 404

### ISSUE THREAD

**Issue by janajaeger** [openSUSE/suse-xsl#490]
## Problem Description

Check https://github.com/SUSE/doc-slesforsap/tree/maintenance/12_SP3/xmlMAIN-SLES4SAP-guide.xml from https://documentation.suse.com/sles-sap/12-SP5/single-html/SLES4SAP-guide/#cha-s4s-configure-rdp ... the "edit source document" link ends in 404. 

The reason for this is a missing / before the actual file name `12_SP3/xmlMAIN...` ... this of course should read `.../xml/MAIN...`.
As this issue can be found across several hundred pages, I suspect rather the stylesheets than the authors are to blame.

Can you check the respective stylesheet code, please?

**Comment by tomschr** [comment]
I've recreated the documentation from the mentioned repo and branch with the latest stylesheet version 2.86.0. I don't get this error. Everything looks fine. :thinking:

**Comment by jfaltenbacher** [comment]
on d.s.c it is still broken. Clicking on 'Edit source documents' results in 404 error

**Comment by tomschr** [comment]
This was fixed with PR #497
