### ISSUE TITLE
Odd space in footer where productname used to be + productname not displayed on book title page

### ISSUE THREAD

**Issue by sknorr** [openSUSE/suse-xsl#50]
The footer used to have the productname in it. However, then came DB5, and with it, `{article,book,set}info` were replaced by just `info`.

The `product` template started to fail and it seems that was not corrected, just adjusted for in some parts of the stylesheets. Another aspect of this is that the productname is not displayed anymore on the title page of books.

The footer should also better handle the case when there really is no productname.

**Comment by tomschr** [comment]
Hmn... do you mean the `product.name` template in `xhtml/titlepage.templates.xsl`? There is neither `{article,book,set}info` nor `info`...

**Comment by sknorr** [comment]
No, I was talking about FO. The template I mean is in fo/pagesetup.xsl .

**Comment by sknorr** [comment]
Tanja just remarked that this should be higher priority... and I agree, especially since the book title page is affected.

**Comment by sknorr** [comment]
Should be fixed for books with commit 0059c34 and commit ef36d4e.
