### ISSUE TITLE
Broken link in the ReadMe file

### ISSUE THREAD

**Issue by navin772** [openSUSE/suse-xsl#525]
## Problem Description
In ReadMe > 1.Requirements for use > DocBook XSL stylesheets from https://github.com/docbook/xsl10-stylesheets (this link does not works) 
It is probably - https://github.com/docbook/xslt10-stylesheets (note the t after xsl)
## Expected Behaviour
Link should open in new tab instead of error.

**Comment by tomschr** [comment]
Thanks @navin772! Very much appreciated. :+1: 

It's fixed now in commit 4d4ad59da.
