### ISSUE TITLE
screen with role="legal" has line-height issues

### ISSUE THREAD

**Issue by keichwa** [openSUSE/suse-xsl#54]
Superfluous empty lines in PDF output.  See attachment.

![Uploading gfdl.png…]()

(((Attachments don't seem to work.)))

**Comment by sknorr** [comment]
@keichwa's example document was from the tuning guide, final page.

![tuning-ugly-screen](https://cloud.githubusercontent.com/assets/5476547/10486622/1d5a98ba-7290-11e5-931a-f4e11bcef3b2.png)

**Comment by sknorr** [comment]
Fixed in 590da259c1b36f548dd5aeedcf422a964888b294.
