### ISSUE TITLE
Linebreak in Footer Due to Long Section Title 

### ISSUE THREAD

**Issue by taroth21** [openSUSE/suse-xsl#56]
Example: HA Admin Guide, Docupdates appendix (https://github.com/SUSE/doc-sleha/blob/develop/xml/ha_docupdates.xml), section title: 'December 2015 (Initial Release of &productname; 12 SP 1)'

**Comment by sknorr** [comment]
@toms: can we somehow make sure that the table cells in the footer don't become higher than a single line? I.e. something like in this pseudo-CSS:
```
.footer {
overflow:hidden;
height: 1em;
}
```
(Note: even with HTML, you'd still probably need to set some odd `display` value, because `table-cell`s behave really different from `block`s.)

**Comment by sknorr** [comment]
This is now part of issue #78 (tracker bug for language feedback).

**Comment by tomschr** [comment]
As discussed with Jana today, as we focus more on SEO, titles need to be shortened anyway.

**Comment by tomschr** [comment]
As discussed with Jana today, this is no tool issue. Writers need to take care of the length. Maybe a `<titleabbrev>` could be added to GeekoDoc.
