### ISSUE TITLE
CJK: Wonky line heights/baselines in lists

### ISSUE THREAD

**Issue by ghost** [openSUSE/suse-xsl#59]
In e.g. Japanese, in lists: the baseline of the ordinal number does not align with the content.

This happens even when a formalpara is added to a list (formalparas use the same sans font definition as the ordinal numbers) => This is not a problem with the font used.

**Comment by tomschr** [comment]
As discussed today, not relevant for suse2022 stylesheets anymore (focusing more on HTML than PDF).
