### ISSUE TITLE
CJK: Replaced Italic Text Is Hard to Distinguish from Regular

### ISSUE THREAD

**Issue by sknorr** [openSUSE/suse-xsl#60]
We replace italic text in CJK languages, because CJK typography does not really know italics. If they are used, they have a negative connotation.

Bold text is replaced by a gray background color (easy to distinguish, but maybe too visible).

Italic text is replaced by dark-gray text, which is barely distinguishable from regular text. Using a lighter gray may make it distinguishable from regular text but may hurt readability. Underlines are no good either (we use those for commands already).

**Comment by tomschr** [comment]
After some discussions, we should try `border-top` (dotted or solid) if that works.

**Comment by sknorr** [comment]
We have had a few changes here, it did not improve by much but it kind of works. Closing.
