### ISSUE TITLE
Make sure CSS/XSLT can cope with xlink:href everywhere

### ISSUE THREAD

**Issue by sknorr** [openSUSE/suse-xsl#61]
`xlink:href` is seemingly allowed everywhere (from the `&haguide;`):

```
<command xlink:show="new" xlink:href="https://code.google.com/p/jing-trang/">jing</command>
<phrase xlink:show="new" xlink:href="https://xmlgraphics.apache.org/fop">FOP</phrase>
```

Our stylesheets were not made for this.

**Edit after Toms's comment 1 from below:**
What I meant was this: Sure it works, but it looks weird. E.g. in HTML:

+ The phrase has blue text instead of green text.
+ The command looks just like a normal command (black text), albeit with a weird double underline.

I have not bothered to check how the PDF version looks so far.

**Comment by tomschr** [comment]
> Our stylesheets were not made for this.

This is only half-way true: XLink is supported if we haven''t overwritten the default templates for inline elements.
In case we've created our own template, we should probably use `xsl:apply-imports` in some way.

**Comment by tomschr** [comment]
Related to susedoc schema. 

After we've clarified if we want to have that or not, these are the possible solutions:

* Forbid it completely.
* Allow XLinks only on certain (inline) elements.
* Allow it completely and delegate any "issues" to the author (if they want it, they are responsible for that).

**Comment by sknorr** [comment]
It might after all not be necessary to fix this... given issue #99. Close this?

**Comment by tomschr** [comment]
Yes, we can close this. :+1:
