### ISSUE TITLE
Cross-book References Formatted as Serif Text instead of Sans

### ISSUE THREAD

**Issue by ghost** [openSUSE/suse-xsl#63]
Unlike "normal" (=working) cross references that are formatted in the given sans font, references to content not contained in the current deliverable are formatted as serifed text.

That is unfortunate, because then the whole scaling logic for mono text fails (which means mono text contained within a title comes out too large). It is also inconsistent.

**Comment by tomschr** [comment]
Not relevant anymore for 2022
