### ISSUE TITLE
Format `command --option` better

### ISSUE THREAD

**Issue by ghost** [openSUSE/suse-xsl#64]
We previously encouraged authors to use constructs like:

```
<para>
  Geeko mumble kale chips <command>fixie <option>--pbr</option></command>.
</para>
```

DocBook 5 does not allow this. This leads to ugly extra space and broken underlines.

We should try to find a stylesheet-based solution for this, such as when there is only a space between such elements, then assume they belong together and format them as one element.

**Comment by tomschr** [comment]
Not relevant anymore.
