### ISSUE TITLE
Create <img> tags for SVGs

### ISSUE THREAD

**Issue by ghost** [openSUSE/suse-xsl#68]
This one is not that relevant, because so far, DAPS always converted SVG => PNG for the HTML version of the documentation. But that does not have to last forever... especially given that modern browsers are now much better at viewing SVGs than FOP is at converting SVGs.

In `suse2013/xhtml/graphics.xsl`, we convert SVGs to `<object/>`s which has not been necessary in HTML for quite some time and may limit what we can do with SVGs.

**Comment by tomschr** [comment]
Not relevant anymore.
