### ISSUE TITLE
Include revision information in our output again

### ISSUE THREAD

**Issue by ghost** [openSUSE/suse-xsl#74]
Having some revision information in the built books again would be great, but since SVN=>Git move, we lack that information.Though it would not be that hard to gather again, even though, it would be harder to write this information directly into the files.
In any case, this kind of revision information could also take the form of a date: "Revision: Commit a3459856 from April 1, 2014" or so would be nice.

We might need the help of DAPS to resolve this. I.e. DAPS could give us some magic parameters which we could then format further: `revision.id` (first applicable option: tag name or short commit ID), `revision.date` (date of the related commit/tag), and `revision.uncommitted` (local changes in the form `0` or `1`).

The issue for DAPS would be to find out where to get this revision information from, within a Git/SVN repo the answer is pretty obvious, but on e.g. OBS, it might be harder to find out, though maybe a cached text file containing the information could help.

**Comment by tomschr** [comment]
Not relevant anymore.
