### ISSUE TITLE
PDF + HTML: screenshots of frameless dialogs or Web screens look weird  

### ISSUE THREAD

**Issue by taroth21** [openSUSE/suse-xsl#77]
because white fades into white and there is no 'frame' around them...

**Comment by taroth21** [comment]
![issue_layout_html](https://cloud.githubusercontent.com/assets/1875958/10998579/58e8be62-8496-11e5-9df0-92f2e91e19de.png)
![issue_layout_pdf](https://cloud.githubusercontent.com/assets/1875958/10998580/59076aa6-8496-11e5-9fdc-f05f84bc9455.png)

**Comment by tomschr** [comment]
As discussed today, this is next to impossible to determine if a screenshot contains a border or not. We think, this is the responsibility of the author who does the screenshot.
