### ISSUE TITLE
XEP: Screens in procedures overlap into left margin

### ISSUE THREAD

**Issue by ghost** [openSUSE/suse-xsl#84]
We have a rather long-standing issue there and are already using a workaround to get this right for the common cases. Since XEP is actually a bit important for building certain languages that FOP does not like... might be worth fixing.

This is part of issue #78 (tracker bug for language feedback).

**Comment by tomschr** [comment]
As discussed today, we think it's a non-issue because:

* author shouldn't rely on an automatic breaking mechanism
* author ensures that the length of a line should not exceed 80 characters (see styleguide)
* author can reduce font size with processing instruction or break on strategic positions
