### ISSUE TITLE
zh_CN: Cross-references to sections

### ISSUE THREAD

**Issue by sknorr** [openSUSE/suse-xsl#85]
*Linguist's note:*
Please globally change the translation for Book “Book Name”, Chapter n “Chapter name”, Section x.y “Section name” to 《localized book name》第 n 章“localized chapter name”中的第 x.y 节“localized section name”'

This is part of issue #78 (tracker bug for language feedback).

**Comment by gao-yan** [comment]
<l:template name="intra-article" text="《%t》"/>
     <l:template name="intra-book" text="《%t》"/>
     <l:template name="intra-chapter" text="第 %n 章 “%t”"/>
     
     <l:template name="intra-sect1" text="第 %n 节 “%t”"/>
     <l:template name="intra-sect2" text="第 %n 节 “%t”"/>
     <l:template name="intra-sect3" text="第 %n 节 “%t”"/>
     <l:template name="intra-sect4" text="第 %n 节 “%t”"/>

**Comment by sknorr** [comment]
Fixed in 2.0.6.
