### ISSUE TITLE
ar: Use Arabic alphabet for alphabetic listings

### ISSUE THREAD

**Issue by ghost** [openSUSE/suse-xsl#89]
_Linguist's note:_
Please follow the Arabic numbering. [And change the color according to the source.]

Not sure why the second one is an issue ... Arabic listings should have green ordinals, but the screenshot shows the ordinals in black... Not sure why.

This is part of issue #78 (tracker bug for language feedback).

**Comment by tomschr** [comment]
Not relevant anymore.
