### ISSUE TITLE
ar: Cross-references come out without text occasionally

### ISSUE THREAD

**Issue by ghost** [openSUSE/suse-xsl#91]
font used in Arabic does not seem to support English text in cross-reference.
- External books have lang=”en” attributes, which cause English words Chapter and Section to be used.
- When xml:lang attribute is set to xml:lang=”ar”, the EN text is lost completely and there does not appear to be gentext words for Chapter or Section included at all.

This is part of issue #78 (tracker bug for language feedback).

**Comment by tomschr** [comment]
Needs to be investigated with current FOP.
