### ISSUE TITLE
Default SUSE Stylesheets should be DB5

### ISSUE THREAD

**Issue by tomschr** [openSUSE/suse-xsl#95]
Currently, our SUSE stylesheets can be more applied for DB4 than DB5. To create the DB5 stylesheets, `make` has to be called in order to create the `suse2013-ns` tree.

From a development perspective, this is an additional step which makes it sometimes confusing and hard to develop.  It would be good to switch from the DB4 stylesheets to DB5 in the future.

@sknorr, @fsundermeyer  What do you think?

**Comment by sknorr** [comment]
> What do I think?

I don't mind the current process and we need to keep DB4 compatibility for the foreseeable future anyway. It does not really matter if we are generating DB4 or DB5 stylesheets. In other words: meh.

**Comment by tomschr** [comment]
Well, I don't mean to through away the DB4 stylesheets. Just to switch the build process: the default should be DB5. This is were we add our changes, test it etc. But the DB4 tree are generated from DB5. At the moment, it is the other way around.

Furhtermore, it is not possible to clone from Git and use the DB5 stylesheets (with the `--styleroot` from daps). You have to go through the build process first which can be forgotten easily.

**Comment by sknorr** [comment]
I have tried using the `-ns` stylesheets for DB4 content. It went pretty well.
Besides the fact that there was an additional message (something like *adding namespace to files* or so), there did not seem to be any adverse effects.

Sooo, proposal: why not always build with the `-ns` version?

**Comment by sknorr** [comment]
Toms says the reason for that is performance. (`addNS`/`stripNS` apparently are very expensive.)

**Comment by sknorr** [comment]
We are going for the "only provide -ns" solution in the suse2020 styles. We are not going to touch any of the 2013 styles. Let's close this then.
